Feature/trackable timestamp
chaintope/glueby pull request #100
Opened 2021-12-06 18:29 UTC by Yamaguchi

This PR add trackable timestamp feature.

2021-12-07 13:04 UTC, azuchi requested changes

2021-12-07 13:04 UTC, azuchi commented on lib/generators/glueby/contract/templates/timestamp_table.rb.erb
> +      t.integer   :timestamp_type, null: false, default: 0
```suggestion
      t.integer  :timestamp_type, null: false, default: 0
```

2021-12-07 13:04 UTC, azuchi commented on lib/glueby/contract/timestamp.rb
>        end
P2Cアドレスにハッシュ値が含まれていることを証明するために、P2PKHアドレスの元になった公開鍵とハッシュ値を計算して返すメソッドがある必要があるかと思います。

2021-12-07 17:27 UTC, Yamaguchi commented on lib/glueby/contract/timestamp.rb
> +        @timestamp_type = timestamp_type
257c015053f73aec7f71f2fd6fa535d7130ac2aeで修正しました。

2021-12-07 17:28 UTC, Yamaguchi commented on lib/glueby/contract/timestamp.rb
> +        funding_tx, @tx = create_txs(@wallet, @prefix, digest_content, @fee_estimator, @utxo_provider, type: @timestamp_type.to_sym)
257c015053f73aec7f71f2fd6fa535d7130ac2aeで修正しました。

2021-12-07 17:29 UTC, Yamaguchi commented on lib/tasks/glueby/contract/timestamp.rake
> +              funding_tx, tx = create_txs(wallet, t.prefix, t.content_hash, Glueby::Contract::FixedFeeEstimator.new, utxo_provider, type: t.timestamp_type.to_sym)
`Glueby::Contract::AR::Timestamp#timestamp_type`から取得した場合はStringで取得されるので、to_symする必要があります。

2021-12-07 17:33 UTC, Yamaguchi commented on lib/glueby/contract/timestamp.rb
> +        @timestamp_type = timestamp_type
UnsupportedDigestTypeについても同様のチェックを行うようにしています。

2021-12-07 18:00 UTC, Yamaguchi commented on lib/glueby/internal/wallet/active_record_wallet_adapter.rb
> +          px = ECDSA::Format::IntegerOctetString.encode(p.x, group.byte_length)
8a82fdcf6e649b1a43484c6749244a32f67b9bf1

2021-12-07 23:54 UTC, azuchi commented on lib/tasks/glueby/contract/timestamp.rake
> +              funding_tx, tx = create_txs(wallet, t.prefix, t.content_hash, Glueby::Contract::FixedFeeEstimator.new, utxo_provider, type: t.timestamp_type.to_sym)
なるほど。

2021-12-08 00:00 UTC, azuchi commented on lib/glueby/internal/wallet/active_record_wallet_adapter.rb
> +          commitment = Tapyrus.sha256(p.to_hex(false).htb + contents.join).bth.to_i(16) % group.order # H(P || contents)
`p.to_hex(false)`の部分ですが、ここは圧縮公開鍵（`p.to_hex(true)`）でいいかと思います。

2021-12-08 04:41 UTC, Yamaguchi commented on lib/glueby/internal/wallet/active_record_wallet_adapter.rb
> +          commitment = Tapyrus.sha256(p.to_hex(false).htb + contents.join).bth.to_i(16) % group.order # H(P || contents)
350ea3f5878af3a0d473b31ea685b2794bd0d477で修正しました。

2021-12-08 06:14 UTC, Yamaguchi commented on lib/glueby/contract/timestamp.rb
>        end
用途が
https://github.com/chaintope/tapyrus-api/pull/158#discussion_r764491923
であれば、

- P2Cアドレスの元になった公開鍵
- P2Cアドレス

を返すことができれば十分(ハッシュ値は不要)と思いましたが、いかがでしょうか。

2021-12-08 06:15 UTC, Yamaguchi commented on lib/glueby/contract/timestamp.rb
>        end
999a7a69b3439359f2d0f84d3426d8a6112bfd24

2021-12-08 06:17 UTC, azuchi commented on lib/glueby/contract/timestamp.rb
>        end
はい、大丈夫です！

2021-12-08 06:48 UTC, azuchi approved these changes

2021-12-08 06:48 UTC, merged