UtxoProvider を使った Token#burn! で、入力と手数量が同額の時、アウトプットが作成されずエラーになる問題(#105)を修正
chaintope/glueby pull request #108
Opened 2021-12-18 15:31 UTC by rantan

fixes #105

2021-12-19 01:54 UTC, azuchi requested changes

2021-12-19 01:54 UTC, azuchi commented on lib/glueby/constants.rb
> +  module Constants
定数であることは分かるので、namespaceとしての`Constants`は不要かなと思いました。

2021-12-19 01:54 UTC, azuchi commented on lib/glueby/contract/token.rb
> +        burn_all_amount_flag = true if sender.balances[color_id.to_hex] - amount == 0
`sender.balances`で毎回`listunspent`が呼び出されるので、変数に入れて使うなどした方が良いかと思います。

2021-12-19 01:54 UTC, azuchi commented on spec/glueby/contract/token_spec.rb
> +          expect(burn_tx.outputs.count).to eq(1)
valueが`DUST_LIMIT`であるかのチェックも追加しましょう。

2021-12-20 07:54 UTC, rantan commented on spec/glueby/contract/token_spec.rb
> +          expect(burn_tx.outputs.count).to eq(1)
3bcd88e で修正しました。

2021-12-20 07:55 UTC, rantan commented on lib/glueby/contract/token.rb
> +        burn_all_amount_flag = true if sender.balances[color_id.to_hex] - amount == 0
dd12207 で修正しました。

2021-12-20 07:55 UTC, rantan commented on lib/glueby/constants.rb
> +  module Constants
57a502e で修正しました。

2021-12-20 08:06 UTC, azuchi approved these changes

2021-12-20 08:06 UTC, merged