Fix 104
chaintope/glueby pull request #109
Opened 2021-12-20 08:23 UTC by rantan

fixes 104

すでに burn 時以外の問題は #108 で funding tx amount を固定の手数量から計算するようにしたことで解消されていました。

2021-12-20 08:45 UTC, azuchi requested changes

2021-12-20 08:45 UTC, azuchi commented on lib/glueby/contract/tx_builder.rb
> +          change_script = Tapyrus::Script.parse_from_addr(UtxoProvider.new.wallet.change_address)
`#create_funding_tx`の方は、引数でuse_utxo_providerを取るようになってるので、取得方法はどちらかに合わせた方がいいかと思いました。

2021-12-20 11:24 UTC, rantan commented on lib/glueby/contract/tx_builder.rb
> +          change_script = Tapyrus::Script.parse_from_addr(UtxoProvider.new.wallet.change_address)
`if Glueby.configuration.use_utxo_provider?` の方が意図が明確なので、僕は好みです。
それでいいですか？

2021-12-20 11:27 UTC, azuchi commented on lib/glueby/contract/tx_builder.rb
> +          change_script = Tapyrus::Script.parse_from_addr(UtxoProvider.new.wallet.change_address)
ok

2021-12-21 02:39 UTC, azuchi approved these changes

2021-12-21 02:39 UTC, merged