Refactor: extract method 'AR::Timestamp#save_with_broadcast'
chaintope/glueby pull request #111
Opened 2022-01-19 05:45 UTC by Yamaguchi

This PR intends to extract the main codes in timestamp.rake as the method `AR::Timestamp#save_with_broadcast`

2022-01-19 06:34 UTC, azuchi requested changes

2022-01-19 06:34 UTC, azuchi commented on lib/glueby/contract/active_record/timestamp.rb
> +        # @param [Glueby::Contract::FixedFeeEstimator] fee estimator
```suggestion
        # @param [Glueby::Contract::FixedFeeEstimator] fee_estimator
```

2022-01-19 06:34 UTC, azuchi commented on lib/glueby/contract/timestamp.rb
> +        end
`glueby.rb`あたりにあるのが良いかと思います。もしくはmoduleにしてincludeするのでも。

2022-01-19 06:34 UTC, azuchi commented on lib/tasks/glueby/contract/timestamp.rake
> +              t.save_with_broadcast(fee_estimator: fee_estimator)
`save_with_broadcast`内で例外をキャッチしてるので、↓のrescueには入らなくなってます。
戻り値がfalseだったら↓のログだすとかですかね？

2022-01-19 14:34 UTC, Yamaguchi commented on lib/glueby/contract/timestamp.rb
> +        end
glueby.rbに移動しました。
(e27ab79)

2022-01-19 14:36 UTC, Yamaguchi commented on lib/tasks/glueby/contract/timestamp.rake
> +              t.save_with_broadcast(fee_estimator: fee_estimator)
例外発生時は、`save_with_broadcast` の中ですでにログを出力しているので、単に次の処理にうつすだけにしました。

2022-01-20 00:50 UTC, azuchi approved these changes

2022-01-20 00:50 UTC, merged