Customize utxo provider parameters with system_informations table
chaintope/glueby pull request #115
Opened 2022-01-27 09:04 UTC by Yamaguchi

2022-01-27 12:00 UTC, Yamaguchi commented
UtxoProvider機能のON/OFF自体もsystem_informationsテーブルで制御できたほうがよいか？

2022-01-28 05:05 UTC, azuchi requested changes

2022-01-28 05:05 UTC, azuchi commented on lib/glueby/utxo_provider.rb
> +      info_value = Glueby::AR::SystemInformation.find_by(info_key: 'utxo_provider_default_value')
`Glueby::AR::SystemInformation.find_by(info_key: 'utxo_provider_default_value')`の処理については、`use_only_finalized_utxo?`と同様に、`SystemInformation`のメソッドとして定義するのが良いかと思います。
（pool_size）も同様。

2022-01-28 06:36 UTC, Yamaguchi commented on lib/glueby/utxo_provider.rb
> +      info_value = Glueby::AR::SystemInformation.find_by(info_key: 'utxo_provider_default_value')
a67be6a73348d9dc5c04ace85071e1077556e7df で修正しています。
また、「データベースへのアクセスを減らすため値をキャッシュする」ことを確認するためのテストを追加しています。

2022-01-28 06:53 UTC, azuchi approved these changes

2022-01-28 06:53 UTC, merged