Refactoring UTXO Provider
chaintope/glueby pull request #116
Opened 2022-01-31 07:25 UTC by bonn1112

https://github.com/chaintope/tapyrus-api-dashboard/issues/95#issue-1102728006
にて、ダッシュボードから、UTXO Providerの情報を取得するため、UTXO Providerを修正しました。

2022-01-31 07:39 UTC, azuchi requested changes

2022-01-31 07:39 UTC, azuchi commented on lib/glueby/utxo_provider.rb
> +      sum, outputs = collect_uncolored_outputs(@wallet, fee + value)
不要な変更です。

2022-01-31 07:39 UTC, azuchi commented on lib/glueby/utxo_provider.rb
> +      txb.fee(fee).change_address(@wallet.change_address)
不要な変更です。

2022-01-31 07:39 UTC, azuchi commented on lib/glueby/utxo_provider.rb
> +      signed_tx = @wallet.sign_tx(tx)
不要な変更です。

2022-01-31 07:39 UTC, azuchi commented on lib/glueby/utxo_provider/tasks.rb
> +        utxo_provider.tpc_amount
そもそも、このメソッド必要ないのでは？

2022-01-31 07:39 UTC, azuchi commented on lib/glueby/utxo_provider/tasks.rb
> +        utxo_provider.current_utxo_pool_size
そもそも、このメソッド必要ないのでは？

2022-01-31 07:39 UTC, azuchi commented on lib/glueby/utxo_provider/tasks.rb
> +        utxo_provider.value_to_fill_utxo_pool
そもそも、このメソッド必要ないのでは？

2022-01-31 07:39 UTC, azuchi commented on lib/glueby/utxo_provider/tasks.rb
> +        utxo_provider.address
そもそも、このメソッド必要ないのでは？

2022-01-31 07:39 UTC, azuchi commented on lib/glueby/utxo_provider.rb
> +      @address ||= @wallet.get_addresses.first || @wallet.receive_address
`address`を`attr_reader`に追加してください。

2022-01-31 22:14 UTC, bonn1112 commented on lib/glueby/utxo_provider.rb
> +      @address ||= @wallet.get_addresses.first || @wallet.receive_address
8fb4ab8　で修正しました。

2022-01-31 22:14 UTC, bonn1112 commented on lib/glueby/utxo_provider/tasks.rb
> +        utxo_provider.address
8fb4ab8　で修正しました。

2022-01-31 22:14 UTC, bonn1112 commented on lib/glueby/utxo_provider/tasks.rb
> +        utxo_provider.value_to_fill_utxo_pool
8fb4ab8　で修正しました。

2022-01-31 22:14 UTC, bonn1112 commented on lib/glueby/utxo_provider/tasks.rb
> +        utxo_provider.current_utxo_pool_size
8fb4ab8　で修正しました。

2022-01-31 22:14 UTC, bonn1112 commented on lib/glueby/utxo_provider/tasks.rb
> +        utxo_provider.tpc_amount
8fb4ab8　で修正しました。

2022-01-31 23:57 UTC, azuchi requested changes

2022-01-31 23:57 UTC, azuchi commented on lib/glueby/utxo_provider.rb
> +      @wallet.balance(false)
他と同様`@wallet`でなく、`wallet`に統一してください。

2022-02-01 00:53 UTC, bonn1112 commented on lib/glueby/utxo_provider.rb
> +      @wallet.balance(false)
00b8f8a で修正しました。

2022-02-01 01:01 UTC, merged