Make timestamp contract creates record on DB when it uses Glueby::Contract::Timestamp#save!
chaintope/glueby pull request #125
Opened 2022-02-17 08:06 UTC by rantan

2022-02-18 01:54 UTC, azuchi requested changes

2022-02-18 01:54 UTC, azuchi commented on lib/glueby/contract/timestamp.rb
> +        @ar.save_with_broadcast(fee_estimator: @fee_estimator, utxo_provider: @utxo_provider)
`save_with_broadcast`の返り値をチェックする必要があります。

2022-02-18 01:54 UTC, azuchi commented on spec/glueby/contract/timestamp_spec.rb
> +      let(:wallet) { TestWallet.new(internal_wallet) }
これを追加するのであれば、このテストも`Use TestWallet`コンテキスト内にある方がいいのでは？

2022-02-21 02:39 UTC, rantan commented on spec/glueby/contract/timestamp_spec.rb
> +      let(:wallet) { TestWallet.new(internal_wallet) }
fixed at [c92f6c4](https://github.com/chaintope/glueby/pull/125/commits/c92f6c4da5370afbaca82193004b19eaba9a0f5a)

2022-02-21 02:40 UTC, rantan commented on lib/glueby/contract/timestamp.rb
> +        @ar.save_with_broadcast(fee_estimator: @fee_estimator, utxo_provider: @utxo_provider)
faise が帰った場合例外を投げるようにしました。 [ebd6138](https://github.com/chaintope/glueby/pull/125/commits/ebd6138b2cde35324e6b18f517104f435f369947)

2022-02-21 02:50 UTC, azuchi commented on lib/glueby/contract/timestamp.rb
> +        @ar.save_with_broadcast(fee_estimator: @fee_estimator, utxo_provider: @utxo_provider)
RDocに記載されている例外と揃って内容です。
また、内部的に複数の例外が発生するのであれば、`save_with_broadcast!`を作って、`save_with_broadcast`は内部的にそれを呼び出す構成にした方が、原因がクリアになると思いますが、どうですか？

2022-02-21 03:04 UTC, rantan commented on lib/glueby/contract/timestamp.rb
> +        @ar.save_with_broadcast(fee_estimator: @fee_estimator, utxo_provider: @utxo_provider)
> また、内部的に複数の例外が発生するのであれば、save_with_broadcast!を作って、save_with_broadcastは内部的にそれを呼び出す構成にした方が、原因がクリアになると思いますが、どうですか？

その方が良いと思います。
そこに手を入れるのであれば、`rescue => e` ですべての例外を拾っている箇所も、想定するエラーだけを拾うようにしたいですね。

2022-02-21 05:29 UTC, rantan commented on lib/glueby/contract/timestamp.rb
> +        @ar.save_with_broadcast(fee_estimator: @fee_estimator, utxo_provider: @utxo_provider)
修正しました。

2022-02-21 06:17 UTC, azuchi approved these changes

2022-02-21 06:18 UTC, merged