Add updating trackable timestamp feature
chaintope/glueby pull request #128
Opened 2022-02-25 07:05 UTC by rantan

Remaining work

* move pay to contract codes into wallet.

2022-02-25 08:13 UTC, azuchi requested changes

2022-02-25 08:13 UTC, azuchi commented on spec/functional/timestamp_spec.rb
> +          expect(update_ar.status).to eq('confirmed')
署名処理を実装しているので、実際にTapryus上でブロードキャストしたトランザクションデータ（有効なトランザクション）をテストデータとして、それと同じ署名データが生成されていることを検証するテストを追加してください。

2022-02-25 08:35 UTC, rantan commented on lib/glueby/contract/timestamp/tx_builder.rb
> +      class TxBuilder
> `TxBuilder` はクラスである必要がないように思えるのでmoduleでいいのでは？

そうですね。修正するつもりでしたが、忘れていました。

> Timestampも同様ですが、これはおそらく既にtimestamp.rbでクラス宣言してるため、moduleにできないのかと思います。であれば、TSみたいな省略形の名前のmoduleにしてしまうのがいいかと思いました。

このような形で class で宣言しても特に不都合は無いと思っています。 module と class の差はインスタンスを生成出来るかどうかくらいしかなかったと思うので、機能的には差がないと考えるためです。

`TS` のような新しいモジュールを宣言した場合、 `Glueby::Contract::Timestamp` との関係性がわかりにくくなるので、今の形のほうが良いと思いますがいかがでしょうか？

2022-02-25 08:36 UTC, rantan commented on lib/glueby/contract/active_record/timestamp.rb
> +        def utxo
修正します。

2022-02-25 08:36 UTC, rantan commented on lib/glueby/contract/timestamp/tx_builder/simeple_tx_builder.rb
> +        class SimpleTxBuilder
修正します。

2022-02-25 08:36 UTC, rantan commented on lib/glueby/contract/active_record/timestamp.rb
> +            if prev.timestamp_type != 'trackable'
後で試そうとメモしていたのを忘れていました、、修正します。

2022-02-25 08:38 UTC, rantan commented on lib/glueby/contract/timestamp.rb
> +        raise Glueby::Error, 'The timestamp tx is not broadcasted yet.' unless @ar
そもそもテストでしか使っていなくて、必要かどうか微妙ですね。確認します。

2022-02-25 08:41 UTC, azuchi commented on lib/glueby/contract/timestamp.rb
> +        raise Glueby::Error, 'The timestamp tx is not broadcasted yet.' unless @ar
なるほど。不要なら削除しますか。必要になったら追加するのでもいいし。

2022-02-25 08:41 UTC, rantan commented on lib/glueby/contract/timestamp/tx_builder/simeple_tx_builder.rb
> +          def set_inputs(utxo_provider)
複数回呼ぶ想定はしていませんでした。1つのタイムスタンプにつき、1つのtx で想定しています。

2022-02-25 08:41 UTC, rantan commented on spec/functional/timestamp_spec.rb
> +          expect(update_ar.status).to eq('confirmed')
追加します。

2022-02-25 08:42 UTC, azuchi commented on lib/glueby/contract/timestamp/tx_builder.rb
> +      class TxBuilder
OKです。

2022-02-25 17:28 UTC, rantan commented on lib/glueby/contract/timestamp.rb
> +        raise Glueby::Error, 'The timestamp tx is not broadcasted yet.' unless @ar
削除しました。

2022-02-25 17:29 UTC, rantan commented on lib/glueby/contract/active_record/timestamp.rb
> +            if prev.timestamp_type != 'trackable'
修正しました。

2022-02-25 17:29 UTC, rantan commented on lib/glueby/contract/timestamp/tx_builder/simeple_tx_builder.rb
> +        class SimpleTxBuilder
修正しました。

2022-02-25 17:29 UTC, rantan commented on lib/glueby/contract/timestamp/tx_builder.rb
> +      class TxBuilder
TxBuilder を module にしました。

2022-02-25 17:29 UTC, rantan commented on lib/glueby/contract/active_record/timestamp.rb
> +        def utxo
修正しました。

2022-02-25 17:29 UTC, rantan commented on spec/functional/timestamp_spec.rb
> +          expect(update_ar.status).to eq('confirmed')
署名処理をウォレット側に移した後に、そちらにテストを追加します。

2022-02-28 01:16 UTC, rantan commented on spec/functional/timestamp_spec.rb
> +          expect(update_ar.status).to eq('confirmed')
追加しました。

[ff59369](https://github.com/chaintope/glueby/pull/128/commits/ff59369f4de25ddd59b3565b72071f7b65d6a624)

2022-02-28 01:45 UTC, rantan commented
latest フラグが機能するように修正しました。
[b0ecf4d](https://github.com/chaintope/glueby/pull/128/commits/b0ecf4d88b7883ebe840f8045d26cff34dcaab18)

2022-02-28 02:08 UTC, azuchi requested changes

2022-02-28 02:21 UTC, rantan commented on lib/glueby/contract/active_record/timestamp.rb
> +              if update_trackable?
timestamp type が :simple か、新規の tracking タイムスタンプを作成する時ですね。

2022-02-28 02:28 UTC, rantan commented on lib/glueby/contract/active_record/timestamp.rb
> +        end
rename しました。
678a81b

古い名前は alias にしました。

2022-02-28 02:34 UTC, azuchi approved these changes

2022-02-28 02:34 UTC, merged