Add a fee estimator taht calculate fees from tx
chaintope/glueby pull request #136
Opened 2022-03-09 05:34 UTC by rantan

and also rename existing FixedFeeEstimator to just Fixed.

2022-03-11 02:24 UTC, azuchi requested changes

2022-03-11 02:24 UTC, azuchi commented on lib/glueby/utxo_provider.rb
> +      @fee_estimator_for_manage = UtxoProvider.config && UtxoProvider.config[:fee_estimator_for_manage] || @fee_estimator
今回、UTXOの補充用にのみ新しいEstimatorを使用するため追加されたのが`fee_estimator_for_manage`で、将来的に他の機能でも利用可能にした場合、`fee_estimator`と`fee_estimator_for_manage`は統合されるという認識で合ってますか？

2022-03-11 02:24 UTC, azuchi commented on spec/glueby/contract/fee_estimator/calc_spec.rb
> +  end
Txサイズの違いによる境界値のテストケースを追加してください。

2022-03-11 02:24 UTC, azuchi commented on spec/glueby/contract/timestamp_spec.rb
> +        expect(txid).to eq 'ebeae6702ac450d9281049047e9110d5c2091e864827a64a84611d042f8eda23'
これは別のPRの内容？

2022-03-11 02:24 UTC, azuchi commented on lib/glueby/utxo_provider/tasks.rb
> +          fee = fee_estimator.fee(dummy_tx(txb.build))
dummy_txは手数料計算のためのダミーTxを生成するだけなので、`TxBuilder`から`Estimator`に実装を移動した方がいいかもしれません。

2022-03-11 02:24 UTC, azuchi commented on README.md
>  It just returns a fixed fee value without any estimation.
新たに追加したEstimatorについての説明も追加してください。

2022-03-14 07:46 UTC, rantan commented on lib/glueby/utxo_provider.rb
> +      @fee_estimator_for_manage = UtxoProvider.config && UtxoProvider.config[:fee_estimator_for_manage] || @fee_estimator
統合は予定していません。utxo pool の管理タスクで使用するための設定が `fee_estimator_for_manage` で、`fee_estimator` は utxo を提供する際に使う想定です。

2022-03-15 06:44 UTC, rantan commented on spec/glueby/contract/fee_estimator/calc_spec.rb
> +  end
境界値というのは、具体的には何を言っていますか？Tx のサイズの違いでロジックが変わるわけではないと思っています。

fee rate が変わって、小数点以下の数値が現れることがありますが、そのケースはテストを記述しています

2022-03-15 06:47 UTC, rantan commented on spec/glueby/contract/timestamp_spec.rb
> +        expect(txid).to eq 'ebeae6702ac450d9281049047e9110d5c2091e864827a64a84611d042f8eda23'
https://github.com/chaintope/glueby/pull/135 のコミットが混ざっていますね。。修正します。

2022-03-15 06:50 UTC, azuchi commented on spec/glueby/contract/fee_estimator/calc_spec.rb
> +  end
あぁ、勘違いでした。気にしないでください。

2022-03-15 09:06 UTC, rantan commented on README.md
>  It just returns a fixed fee value without any estimation.
追加しました

2022-03-15 09:06 UTC, rantan commented on lib/glueby/utxo_provider/tasks.rb
> +          fee = fee_estimator.fee(dummy_tx(txb.build))
移動しました

2022-03-15 09:06 UTC, rantan commented on spec/glueby/contract/timestamp_spec.rb
> +        expect(txid).to eq 'ebeae6702ac450d9281049047e9110d5c2091e864827a64a84611d042f8eda23'
修正しました

2022-03-15 09:06 UTC, rantan commented on lib/glueby/contract/fee_estimator/fixed.rb
> +        def initialize(fixed_fee: Fixed.default_fixed_fee || 10_000)
定数にしました

2022-03-15 09:07 UTC, rantan commented on lib/glueby/contract/fee_estimator/calc.rb
> +      class Calc
変更しました

2022-03-15 09:22 UTC, azuchi commented on lib/glueby/contract/tx_builder.rb
>        def dummy_issue_tx_from_out_point
`dummy_tx`の移動に伴いこっちも移動する？

2022-03-15 10:04 UTC, rantan commented on lib/glueby/contract/tx_builder.rb
>        def dummy_issue_tx_from_out_point
特定の contract に依存しているので、スルーしました。
持っていくにしても名前は考えたいですね。

2022-03-16 00:21 UTC, azuchi commented on lib/glueby/contract/tx_builder.rb
>        def dummy_issue_tx_from_out_point
まぁ一旦置いとくか

2022-03-16 00:21 UTC, azuchi approved these changes

2022-03-16 00:21 UTC, merged