Make token issue and multiple transfer feature possible to work with  the tx has a lot of outputs
chaintope/glueby pull request #141
Opened 2022-04-22 16:58 UTC by rantan

This PR makes token contract to work with FeeEstimator::Auto to calculate minimum fee to be accepted while broadcasting. Then, adds functionality to UtxoProvider to provide insufficient amount of inputs up to enough amount.

2022-04-25 02:39 UTC, azuchi requested changes

2022-04-25 02:39 UTC, azuchi commented on spec/functional/token_spec.rb
> +        # It allow to split up to 24. If it set over 24, it raises the min relay fee error.
`Fixed`でmin relay fee errorが発生するテストケースはありますか？

2022-04-25 03:18 UTC, rantan commented on lib/glueby/contract/fee_estimator.rb
> +          input.script_sig = Tapyrus::Script.parse_from_payload(('00' * 100).htb)
実際の tx の script_sig を見たら 100 バイトだったためこうしました。

2022-04-25 03:19 UTC, rantan commented on lib/glueby/contract/tx_builder.rb
> +        Tapyrus::Key
誤って貼り付けたかなにかしたんだと思います。消します。

2022-04-25 03:21 UTC, rantan commented on lib/glueby/contract/fee_estimator/auto.rb
> +            # Tapyrus Core requires more over 1 from the just amount fee if the tx has colored outputs
colored coin の発行アウトプットがある tx だけ、mempool に入れるときの検証で、必要な手数料が min relay fee に対して 1 以上大きくなっている必要があるようです。

以下が該当箇所です。
https://github.com/chaintope/tapyrus-core/blob/357b8ff8274ef385beb78b5cc7cdd3c098f13418/src/validation.cpp#L1050

2022-04-25 03:21 UTC, rantan commented on lib/glueby/utxo_provider.rb
> +    def collect_uncolored_outputs(wallet, amount, excludes = [])
追加します

2022-04-25 04:47 UTC, rantan commented on lib/glueby/contract/tx_builder.rb
>            sum_tpc
消します。

2022-04-25 05:45 UTC, rantan commented on spec/functional/token_spec.rb
> +        # It allow to split up to 24. If it set over 24, it raises the min relay fee error.
作っていないですね。追加します。

2022-04-25 13:01 UTC, Yamaguchi requested changes

2022-04-25 14:14 UTC, Yamaguchi commented on lib/glueby/contract/tx_builder.rb
> +            target_amount: 0,
target_amountが0、current_amountがoutput.valueになってますが、逆では？

2022-04-25 16:57 UTC, Yamaguchi commented on lib/glueby/contract/tx_builder.rb
> +        UtxoProvider.new.wallet.sign_tx(tx, prev_txs) if Glueby.configuration.use_utxo_provider?
大したコストになるわけではないですが、`UtxoProvider.new`を2回実行しているのが気になります。

2022-04-26 00:56 UTC, rantan commented on lib/glueby/contract/fee_estimator/auto.rb
> +            # Tapyrus Core requires more over 1 from the just amount fee if the tx has colored outputs
input を見ようとするとちょっとややこしくなるなと思ってとりあえず +1 する感じにしていました。

input を見るようにしてみます。

2022-04-26 00:56 UTC, rantan commented on lib/glueby/contract/fee_estimator/auto.rb
> +          if tx.outputs.find { |i| i.script_pubkey.colored? }
行けると思います。修正します。

2022-04-26 00:58 UTC, rantan commented on lib/glueby/contract/token.rb
>            funding_tx = create_funding_tx(wallet: issuer, only_finalized: only_finalized?)
今回の修正の目的が split に大きな値が設定されることによる手数料不足の解消だったので、tx の形が固定で手数料不足になる懸念のない funding_tx にはとくに変更を加えませんでした。

2022-04-26 00:58 UTC, rantan commented on lib/glueby/contract/fee_estimator/auto.rb
> +          fee = ((tx.to_payload.bytesize / 1000.0) * fee_rate).ceil
使うように修正します。

2022-04-26 01:19 UTC, rantan commented on lib/glueby/contract/tx_builder.rb
> +        UtxoProvider.new.wallet.sign_tx(tx, prev_txs) if Glueby.configuration.use_utxo_provider?
Singletonにしますかね。

2022-04-26 01:20 UTC, rantan commented on lib/glueby/utxo_provider.rb
>        utxos = wallet.list_unspent.select { |o| !o[:color_id] && o[:amount] == default_value }
そうですね。試してみます。

2022-04-26 01:23 UTC, rantan commented on lib/glueby/contract/tx_builder.rb
> +            target_amount: 0,
カラードコインの発行 tx ですので、target_amount は 0 であっていると思います。TPC なので。
tx.inputs には funding_tx のアウトプットが指定されているので、その時点での amount はそのアウトプットの value なのでこのような指定になっています。

2022-04-26 07:14 UTC, rantan commented on lib/glueby/contract/fee_estimator/auto.rb
> +            # Tapyrus Core requires more over 1 from the just amount fee if the tx has colored outputs
そもそもこの Tapyrus Core の仕様って意図されたものなんですかね？条件判定で 0 にするのが自然かと思いますが。
あと、tpc のinput と output のバランスが取れているかはカラードコインの発行かどうかにかかわらずチェックするはずなので、このチェック自体が蛇足にも思います。

2022-04-26 07:23 UTC, rantan commented on lib/glueby/contract/fee_estimator/auto.rb
> +            # Tapyrus Core requires more over 1 from the just amount fee if the tx has colored outputs
input を見るようにする対応やっぱりややこしくなりますし、上の疑問もあるので今回は見送りたい気持ちです。どうでしょう？

2022-04-26 07:24 UTC, rantan commented on lib/glueby/contract/token.rb
>                             issue_nft_token(issuer: issuer)
NFT の場合は split パラメーターがないので、手数料不足のエラーになる懸念がないので今回は対応していません。

2022-04-26 07:26 UTC, azuchi commented on lib/glueby/contract/fee_estimator/auto.rb
> +            # Tapyrus Core requires more over 1 from the just amount fee if the tx has colored outputs
挙動については、naviaに確認してみてください。ただ、今回の見送りは了解です。TODOコメント記載しておいてもらえると。

2022-04-27 03:02 UTC, rantan commented
@azuchi @Yamaguchi もろもろ修正しました！

2022-04-27 05:08 UTC, rantan commented on lib/glueby/contract/tx_builder.rb
> +            target_amount: 0,
target_amount は fee とお釣りを覗いた output で必要な TPC を設定する想定なので、TPC の送金がない TX では 0 になります。

2022-04-27 07:19 UTC, merged

2022-04-28 05:57 UTC, Yamaguchi commented on lib/glueby/contract/tx_builder.rb
> +            target_amount: 0,
理解しました。