Feature/token metadata
chaintope/glueby pull request #149
Opened 2022-07-04 04:23 UTC by Yamaguchi

2022-07-07 02:06 UTC, azuchi requested changes

2022-07-07 02:06 UTC, azuchi commented on lib/glueby/contract/token.rb
> +              sign_to_p2c_output(issuer, tx, funding_tx, payment_base, metadata)
再発行可能なトークンタイプの場合、`color_id`に対してunique制約が付いているので、ここでunique制約のエラーが発生する可能性がありますよね？

* その場合、エラーハンドリングは大丈夫でしょうか？
* また、このケースのテストを追加してください。

2022-07-07 02:06 UTC, azuchi commented on lib/glueby/contract/token.rb
>        attr_reader :color_id
トークンに紐付けられたメタデータを取得する際のコードは不要ですか？

2022-07-07 06:50 UTC, rantan requested changes
reissue の時も metadata ありのトークンの場合、p2c アドレス向けの scriptsig を作る必要があると思いますが、作っていなさそうに見えます。

2022-07-07 06:56 UTC, rantan requested changes
UtxoProviderを使うケースのテストと、`spec/functional` 以下に機能テストの追加もお願いします。

2022-07-07 17:37 UTC, Yamaguchi commented on lib/glueby/contract/token.rb
> +              Glueby::Contract::AR::TokenMetadata.create(
57ccc2979699f1a0129eac214579bc22b85b319b で修正しました

2022-07-07 17:37 UTC, Yamaguchi commented on lib/glueby/contract/token.rb
> +              Glueby::Contract::AR::TokenMetadata.create(
57ccc2979699f1a0129eac214579bc22b85b319b で修正しました

2022-07-07 17:38 UTC, Yamaguchi commented on lib/glueby/contract/token.rb
> +              sign_to_p2c_output(issuer, tx, funding_tx, payment_base, metadata)
86aeaeac727f3de29f0db0235a87fbd5e50a1058 で修正しました。

2022-07-07 17:38 UTC, Yamaguchi commented on lib/glueby/util/digest.rb
> +      def digest_content(content, digest)
11988af0a9bc6e840bcabae4e7563c65e8b9f66b

2022-07-07 17:40 UTC, Yamaguchi commented
> reissue の時も metadata ありのトークンの場合、p2c アドレス向けの scriptsig を作る必要があると思いますが、作っていなさそうに見えます。

1de2af053296468f3fcf6494bc6ee92250e3a89f で対応してます。

2022-07-07 18:09 UTC, Yamaguchi commented
> UtxoProviderを使うケースのテストと、`spec/functional` 以下に機能テストの追加もお願いします。

fe127135204c90fd2145b652d5df0da9d968980b と a0dc2916ed0791d39e3f421047c1320e2cbe963e でテストケースを追加しました。

2022-07-08 04:31 UTC, Yamaguchi commented on lib/glueby/contract/token.rb
>        attr_reader :color_id
TapyrusAPI側で対応しようかと考えてます。

https://github.com/chaintope/tapyrus-api/pull/268/commits/f5f9f937f95683e39f7c4df31c1da9ad20c89127

`Glueby::Wallet#balance` の仕様は変えたくないので、Glueby側で実装するに場合は新しくメソッドをつくるなどを検討します。

2022-07-08 05:56 UTC, Yamaguchi commented
再発行可能なトークンでは、発行のたびにFunding Txが必要となる理由についてコメントに追記しました。
          
55d272d1d05cc48262b37d571cd555764c16fa6b

2022-07-10 05:54 UTC, Yamaguchi commented on lib/glueby/contract/token.rb
>        attr_reader :color_id
https://github.com/chaintope/glueby/pull/149/commits/8e2009485751c071558ac4a4f15c52665a6383aa

2022-07-11 05:00 UTC, rantan commented on lib/glueby/util/digest.rb
> +    module Digest
了解です。
Timestamp でしか使わないので、ユーティリティとして切り出す必要はないかと思うので、戻したほうが良いかと思いました。

2022-07-11 06:57 UTC, rantan commented
p2c ドレスの生成については、ウォレット側でテストしているので, トークン側での検証は不要と思いました。お騒がせしました。

2022-07-11 06:58 UTC, rantan approved these changes

2022-07-11 10:10 UTC, Yamaguchi commented on lib/glueby/util/digest.rb
> +    module Digest
459a851136645ee9084ca5cf02936aba7c683dbd で戻しました。

2022-07-13 06:54 UTC, azuchi requested changes

2022-07-13 06:54 UTC, azuchi commented on lib/glueby/contract/token.rb
>          # @raise [UnspportedTokenType] if token is not supported.
直接関係ないですが、ついでにTypo修正してもらえると助かります。

```suggestion
        # @raise [UnsupportedTokenType] if token is not supported.
```

2022-07-13 06:54 UTC, azuchi commented on lib/glueby/contract/token.rb
> +        def sign_to_p2c_output(issuer, tx, funding_tx, payment_base, metadata)
こちらのメソッドもパブリックメソッドなので、メソッドシグネチャ追加してください。

2022-07-13 06:54 UTC, azuchi commented on lib/glueby/contract/token.rb
> +      def validate_reissuer(wallet:, token_metadata: nil)
検証結果を返すメソッドなので`valid_reissuer?`というネーミングの方が良いかと思いました。

2022-07-13 06:54 UTC, azuchi commented on lib/glueby/contract/token.rb
> +      # @reutrn [Boolean] true if the wallet is the issuer of this token
```suggestion
      # @return [Boolean] true if the wallet is the issuer of this token
```

2022-07-13 06:54 UTC, azuchi commented on lib/glueby/contract/token.rb
>          addresses = wallet.internal_wallet.get_addresses
`internal_wallet`自体に`has_address?`を作って、ARAdaptorではwhere句で判定した方が、後続の処理でループ回すより速くなると思いますが、どうでしょう？

2022-07-13 06:54 UTC, azuchi commented on lib/glueby/contract/token.rb
> +            end
トランザクション境界を制御するコードが追加されていますが、この挙動を検証するテストコードはありますか？

2022-07-14 17:09 UTC, Yamaguchi commented on lib/glueby/contract/token.rb
> +      # @reutrn [Boolean] true if the wallet is the issuer of this token
0367497d5b51be04589e90627c5158540590792c で修正してます。

2022-07-14 17:10 UTC, Yamaguchi commented on lib/glueby/contract/token.rb
>          addresses = wallet.internal_wallet.get_addresses
88d04103c5afb5c1c8adc3e036a3edee2568c1c2 で修正しました。

2022-07-14 17:10 UTC, Yamaguchi commented on lib/glueby/contract/token.rb
> +      def validate_reissuer(wallet:, token_metadata: nil)
88d04103c5afb5c1c8adc3e036a3edee2568c1c2 で修正しました。

2022-07-14 17:10 UTC, Yamaguchi commented on lib/glueby/contract/token.rb
> +        def sign_to_p2c_output(issuer, tx, funding_tx, payment_base, metadata)
e3e4ac050a4d0d960445c6278736af5fadf39c76 でコメント追加しました。

2022-07-15 04:58 UTC, Yamaguchi commented on lib/glueby/contract/token.rb
> +            end
18b73bf178919a0103059c8fd837f65a5abfe08e にテストケースを追加しました。

2022-07-19 01:13 UTC, azuchi commented on spec/glueby/contract/token_spec.rb
> +            expect { subject }.to raise_error(RuntimeError).and change(Glueby::Contract::AR::TokenMetadata, :count).by(0)
FundingのUTXOの変更はコミットされていることの検証を追加すると良いかと思います。

2022-07-20 13:25 UTC, Yamaguchi commented on spec/glueby/contract/token_spec.rb
> +            expect { subject }.to raise_error(RuntimeError).and change(Glueby::Contract::AR::TokenMetadata, :count).by(0)
Funding tx のinputに使用したUTXOを確認するコードを追加しました。
(405943995aab9f188b3e6b7c1ad6737d41453da8)

funding_txのoutputsについてはmetadataから生成したpay to contractへのUTXOに対しては `Glueby::Internal::Wallet::AR::Utxo` へ登録が行われないので、確認が難しい。

2022-07-21 08:35 UTC, azuchi approved these changes

2022-07-21 08:35 UTC, merged