Lock utxo with SKIP LOCKED option
chaintope/glueby pull request #157
Opened 2022-09-08 04:22 UTC by Yamaguchi

This works in the case the application uses MySQL (or Postgresql).

2022-09-10 06:53 UTC, Yamaguchi commented
mysqlのDocker イメージをダウンロードしてテストするようにしてます。

2022-09-13 05:25 UTC, Yamaguchi commented
https://github.com/chaintope/tapyrus-api/issues/283

2022-09-27 06:36 UTC, rantan requested changes

2022-09-27 06:36 UTC, rantan commented on lib/glueby/internal/wallet/mysql_wallet_adapter.rb
> +            record&.update!(status: :spending)
下みたいな雰囲気で１クエリにならないかなと思ったけど、postgresql のように "RETURNING" がつかえないようなので、結局アップデートしたレコードを別クエリで取得する必要があってあまり意味がない気がしまして諦めました。。。というただの報告です。
```ruby
subquery = AR::Utxo.lock("FOR UPDATE SKIP LOCKED").select('id').where(txid: utxo[:txid], index: utxo[:vout], status: :finalized).to_sql
            record = AR::Utxo.find_by_sql(["UPDATE #{AR::Utxo.table_name} SET status = ? WHERE id IN (#{subquery})", AR::Utxo.statuses[:spending]])
```

2022-09-27 06:36 UTC, rantan commented on lib/glueby/internal/wallet/mysql_wallet_adapter.rb
> +            record = AR::Utxo.lock("FOR UPDATE SKIP LOCKED").find_by(txid: utxo[:txid], index: utxo[:vout], status: :finalized)
`finalized` を指定していますが、finalized していない utxo をロックしたいシーンも今後あるかと思うので、なくてもよいのではと思いましたが、いかがでしょうか？

2022-09-28 04:20 UTC, Yamaguchi commented on lib/glueby/internal/wallet/mysql_wallet_adapter.rb
> +            record = AR::Utxo.lock("FOR UPDATE SKIP LOCKED").find_by(txid: utxo[:txid], index: utxo[:vout], status: :finalized)
f345ceecdd4e6765ffb349bc18817567fb255392 で:broadcasted(と:init)もlockできるようにしました。

2022-09-28 04:33 UTC, Yamaguchi commented on lib/glueby/internal/wallet/active_record_wallet_adapter.rb
> +        def lock_unspent(wallet_id, utxo)
削除しました(https://github.com/chaintope/glueby/commit/f345ceecdd4e6765ffb349bc18817567fb255392)

2022-10-04 06:57 UTC, rantan requested changes

2022-10-04 06:57 UTC, rantan commented on lib/glueby/utxo_provider.rb
> +        if wallet.lock_unspent(output)
tx のブロードキャストに失敗した場合、unlock する仕組みが必要だと思いましたが、いかがでしょう？

2022-10-13 05:11 UTC, rantan requested changes

2022-10-13 05:11 UTC, rantan commented on lib/glueby/utxo_provider.rb
> +        if wallet.lock_unspent(output)
> ただし、Wallet#lock_unspent を実行するとUtxoのレコードが :spending に更新されたままとなるので、ブロードキャストに失敗した場合にステータスを戻す処理が本来は必要なのですが、broadcastedに戻すかfinalizedに戻すかわからないので、実装が難しいかなと考えています。

broadcasted, finalized などとは別のカラムで spending のステータスは管理した方が良いように思います。
例えば locked_at のようなカラムを加えて、 #lock_unspent の中で値をセットするようにするのはいかがでしょうか？

2022-10-13 05:24 UTC, rantan commented on lib/glueby/utxo_provider.rb
> +        if wallet.lock_unspent(output)
そもそも、RDB のトランザクション制御がちゃんとしていれば、 spending のままになるケースはないんですっけ、、？
それとは別にしても、ブロック同期のバッチ処理と競合する可能性があるので、 spending の管理をするカラムは分けた方が良いとは思いますが。

2022-10-14 05:08 UTC, merged