Refactor tx building codes
chaintope/glueby pull request #161
Opened 2023-03-23 04:39 UTC by rantan

* Add Internal::TxBuilder and use it in every contract classes
* Remove Glueby::Contract::TxBuilder

2023-04-01 01:25 UTC, azuchi requested changes

2023-04-01 01:25 UTC, azuchi commented on spec/glueby/internal/tx_builder_spec.rb
> +    end
`split_value` メソッドの`if value < split`条件のテストケースってありますか？

2023-04-01 01:25 UTC, azuchi commented on spec/glueby/internal/tx_builder_spec.rb
> +    end
インプットのトークンの一部を焼却する場合、差額分のアウトプットができる場合があるのでは？

2023-04-03 00:52 UTC, rantan commented on spec/glueby/contract/timestamp_spec.rb
> +          expect(internal_wallet).to receive(:broadcast).twice { |tx| tx }
ブロックを渡さないと #broadcast の返り値が nil になります。これで引数で受け取った tx を返すようになります。

2023-04-03 00:52 UTC, rantan commented on lib/glueby/contract/tx_builder.rb
> -end
削除します。

2023-04-03 00:59 UTC, azuchi commented on spec/glueby/contract/timestamp_spec.rb
> +          expect(internal_wallet).to receive(:broadcast).twice { |tx| tx }
なるほど。

2023-04-03 01:04 UTC, rantan commented on spec/glueby/internal/tx_builder_spec.rb
> +    end
ないですね。追加します。

2023-04-03 01:04 UTC, rantan commented on spec/glueby/internal/tx_builder_spec.rb
> +    end
その処理はおつりのアウトプットを追加する処理で行うので、このメソッドでは扱っていません。

2023-04-03 05:04 UTC, rantan commented on lib/glueby/contract/tx_builder.rb
> -end
[d82b940](https://github.com/chaintope/glueby/pull/161/commits/d82b940faae834a132a3a959b560f63fa9a4ff56) 削除しました。

2023-04-03 05:04 UTC, rantan commented on lib/glueby/contract/timestamp/tx_builder/simple.rb
> +              return self if fee == 0
[c15969c](https://github.com/chaintope/glueby/pull/161/commits/c15969c452af3019407ad26b57cd2e24123be419) 追加しました。

2023-04-03 05:05 UTC, rantan commented on lib/glueby/internal/wallet.rb
> +      def collect_uncolored_outputs(amount = nil, label = nil, only_finalized = true, shuffle = false)
[9658e06](https://github.com/chaintope/glueby/pull/161/commits/9658e06cf8679df242959b3b1cd8ec52fff9b80b) 追加しました

2023-04-03 05:05 UTC, rantan commented on lib/glueby/internal/wallet.rb
> +      # @param [Boolean] shuffle The flag to shuffle UTXO before collecting
[9658e06](https://github.com/chaintope/glueby/pull/161/commits/9658e06cf8679df242959b3b1cd8ec52fff9b80b) 追加しました

2023-04-03 05:05 UTC, rantan commented on lib/glueby/internal/tx_builder.rb
> +        signer_wallet:,
[c81191a](https://github.com/chaintope/glueby/pull/161/commits/c81191a80b5a8afbbc1a3b3338238e5c0d47e462) 変更しました。

2023-04-03 05:05 UTC, rantan commented on spec/glueby/internal/tx_builder_spec.rb
> +    end
[4d13fa6](https://github.com/chaintope/glueby/pull/161/commits/4d13fa6815e78a6872d8bee794ada16fd45bc60c) 追加しました。

2023-04-03 17:12 UTC, Yamaguchi requested changes

2023-04-03 17:12 UTC, Yamaguchi commented on lib/glueby/internal/tx_builder.rb
> +      def split_value(value, split)
と思ったのですが、以前からエラーとなる動作っぽいので一旦無視がよいか。

2023-04-04 01:08 UTC, rantan commented on lib/glueby/internal/tx_builder.rb
> +          tx = sender_wallet.broadcast(tx)
アプリ側でエラーが発生した場合に、すでにブロードキャスト済みのトランザクションを取り消せないのは、ブロードキャストを tx builder の外で行った場合も同じだと思います。

これまでの処理も、コントラクトのメインの tx とは独立して funding tx のブロードキャストを実行しています。そういう意味ではあまり差はないと思います。

2023-04-04 01:19 UTC, azuchi commented on lib/glueby/contract/active_record/timestamp.rb
> -            end
リンクが指してる先が特定のコードを指してないようなので、具体的な場所を教えてください。

2023-04-04 01:19 UTC, rantan commented on lib/glueby/internal/tx_builder.rb
> +          tx = sender_wallet.broadcast(tx)
エラー時のリカバリという意味では、UtxoProcider を使っている場合は、funding tx でsender に送った UTXO を再び UtxoProvider のウォレットへ戻す tx を発行する処理を追加するという事もできそうですね。

UtxoProvider を有効にしているのに、ユーザーのウォレットに TPC の残高が生まれてしまう可能性があるので、その問題は解消できそうです。

2023-04-04 01:25 UTC, rantan commented on lib/glueby/contract/active_record/timestamp.rb
> -            end
lib/glueby/contract/timestamp/tx_builder/simple.rb 35 行目に呼んでいる Internal::TxBuilder#add_utxo_to の中でブロードキャストしています。

2023-04-04 01:30 UTC, azuchi commented on lib/glueby/internal/tx_builder.rb
> +          tx = sender_wallet.broadcast(tx)
`TxBuilder`という名前のクラスがブロードキャストしてるのが気になるんじゃないかと思います。自分もちょっと気になりました。名前から推測する責務はTxの構築までだと思うので。

リファクタリング前のTxBuilderは、tapryusrbのTxBuilderのような純粋のTxの構築するというのではなく、コントラクトモジュールとして実装されてるけど名前がTxBuilderなのが、整合性とれてなかったのかなと。で、今回tapyrusrbのTxBuilderを継承する形で実装したので、TxBuilderに寄せるなら責務はTxの構築までにした方が良いかと思います。

2023-04-04 01:39 UTC, rantan commented on lib/glueby/internal/tx_builder.rb
> +          tx = sender_wallet.broadcast(tx)
TxBuilder がブロードキャストするのは直観に反しているというのは同意します。
ただ、それについても微妙な議論があるなとは思います。

TxBuilder で作りたいのは、Timestamp, Token, などのコントラクトのための tx であって、 funding_tx はそれを構成するための前準備として必要になるものです。

また、funding tx のブロードキャストを実行するまで funding tx の txid が確定しないため、コントラクトの tx を完成させるためには先に funding tx をブロードキャストする必要があるという事情もあります。

2023-04-04 01:39 UTC, rantan commented on lib/glueby/internal/tx_builder.rb
> +          tx = sender_wallet.broadcast(tx)
> また、funding tx のブロードキャストを実行するまで funding tx の txid が確定しないため
これは FeeProvider を利用する場合の話です。

2023-04-04 02:45 UTC, azuchi commented on lib/glueby/internal/tx_builder.rb
> +          tx = sender_wallet.broadcast(tx)
`ContractBuilder`みたいに名前を変更しましょうか。あとブロードキャストが発生するメソッド名を破壊的メソッドにする。

2023-04-04 05:42 UTC, Yamaguchi approved these changes

2023-04-04 07:05 UTC, rantan commented on lib/glueby/internal/tx_builder.rb
> +          tx = sender_wallet.broadcast(tx)
[54db94c](https://github.com/chaintope/glueby/pull/161/commits/54db94cf73f6d108ab7383e053d64196829029bd) 変更しました。

2023-04-04 07:35 UTC, azuchi approved these changes

2023-04-04 08:38 UTC, merged