Fix insufficient fee error with bearing fee by wallets
chaintope/glueby pull request #170
Opened 2023-04-24 08:41 UTC by rantan

トークンの送金トランザクションで、手数料を計算するために利用する一時的なトランザクションにトークンのお釣りのためのアウトプットが追加されないために、手数料が不足するTXを作成していました。
これを修正します。

2023-04-26 12:17 UTC, rantan commented on lib/glueby/utxo_provider.rb
> -      target_amount += DUST_LIMIT if target_amount < DUST_LIMIT
おつりが DUST_LIMIT より小さくなりそうな場合は、インプットを追加しておつりの金額を増やして dust アウトプットが作られないようにしていましたが、tapyrusrb の TxBuilder のやり方に合わせて、DUST_LIMIT を下回るおつりは手数料として支払ってしまう方針に統一しました。

2023-04-28 07:30 UTC, azuchi requested changes

2023-04-28 07:30 UTC, azuchi commented on lib/glueby/internal/contract_builder.rb
> +            script_pubkey: Tapyrus::Script.new << Tapyrus::Script::OP_RETURN
```suggestion
            script_pubkey: Tapyrus::Script.new << Tapyrus::Opcodes::OP_RETURN
```

2023-04-28 07:30 UTC, azuchi commented on spec/functional/timestamp_spec.rb
> +          end.to change { Glueby::UtxoProvider.instance.wallet.list_unspent.count }.by(-2)
これが増えた理由って何ですか？

2023-04-28 07:30 UTC, azuchi commented on spec/glueby/contract/token_spec.rb
> +            expect(tx.inputs.count).to eq(3)
インプットの構成について、以前と同様にコメントを書いておいてください。

2023-05-01 01:07 UTC, rantan commented on spec/functional/timestamp_spec.rb
> +          end.to change { Glueby::UtxoProvider.instance.wallet.list_unspent.count }.by(-2)
変更前は以下のような tx を作っていました。

* 入力: 2000 tapyrus
* 出力: 1000 tapyrus
* fee: 1000 tapyrus
* FeeEstimator の設定: 2000 tapyrus に固定

手数料として 2000 tapyrus を支払う必要がある設定ですが、 1000 tapyrus だけを支払う挙動をしていました。
実際にはそれでも手数料として十分なのでエラーにはなっていません。

それが、ContractBuilder L280 に追加された

```
raise Contract::Errors::InsufficientFunds if change < 0
```

の影響でエラーになるように挙動が変わりました。
このエラーを回避するために、`Glueby::Contract::Timestamp::TxBuilder::Trackable` を修正して tx の入力を本来必要な 3000 tapyrus になるように修正しました。この入力を作るために 2 つぶんの UTXO を消費するようになりました。

2023-05-01 01:20 UTC, rantan commented on spec/glueby/contract/token_spec.rb
> +            expect(tx.inputs.count).to eq(3)
75ebb8b で修正しました

2023-05-01 01:20 UTC, rantan commented on lib/glueby/internal/contract_builder.rb
> +            script_pubkey: Tapyrus::Script.new << Tapyrus::Script::OP_RETURN
https://github.com/chaintope/glueby/commit/75ebb8b857a21acbe522f5c5eff7ffcb7284c2f5 で修正しました

2023-05-01 01:20 UTC, rantan commented on lib/glueby/contract/timestamp/tx_builder/trackable.rb
> +          private
https://github.com/chaintope/glueby/commit/75ebb8b857a21acbe522f5c5eff7ffcb7284c2f5 で修正しました

private で統一しました。

2023-05-01 01:49 UTC, azuchi approved these changes

2023-05-01 17:14 UTC, Yamaguchi requested changes

2023-05-01 17:14 UTC, Yamaguchi commented on spec/functional/token_spec.rb
> +          expect(receiver.balances(false)[token.color_id.to_hex]).to be_nil
NFTの場合だけburn!後のTPCの確認
```
if fee_estimator.is_a?(Glueby::Contract::FeeEstimator::Fixed)
  expect(sender.balances(false)['']).to eq(before_balance - fee * 3)
end
```
が無いように見えますが、理由ありますか？

2023-05-02 02:50 UTC, rantan commented on spec/functional/token_spec.rb
> +          expect(receiver.balances(false)[token.color_id.to_hex]).to be_nil
特に理由はないです。もともとそのテストがなかったのでないままになっているんだと思います。せっかくなので追加しておきます。

2023-05-02 03:24 UTC, rantan commented on spec/functional/token_spec.rb
> +          expect(receiver.balances(false)[token.color_id.to_hex]).to be_nil
[ea943da](https://github.com/chaintope/glueby/pull/170/commits/ea943da4ea746816bc214e35375ee6fae39bc629) で追加しました。

2023-05-03 07:16 UTC, Yamaguchi approved these changes

2023-05-08 01:21 UTC, merged