Use auto fulfil inputs feature in token issue and transfer
chaintope/glueby pull request #172
Opened 2023-05-02 08:38 UTC by rantan

We are going to remove use_auto_fee option. The functionality of use_auto_fee is going to be included to auto_fulfill_inputs feature.

This PR includes the difference of #170. After #170 merged, this PR will be rebased on the master HEAD and turn into normal PR from draft.

2023-05-08 05:36 UTC, azuchi reviewed
`token.rb`の213行目の
```ruby
# FIXME: It is enough to add just one UTXO here. Funding for fee should care by use_auto_fee feature. But, here add all UTXOs in issuer's wallet, if fee provider is enabled.
```

の説明への影響はありませんか・

2023-05-08 05:36 UTC, azuchi commented on lib/glueby/contract/token.rb
>          if token_metadata
`burn`や`multi_transfer!`で、`use_auto_fee`が残ってるのはどうする予定ですか？

2023-05-08 05:40 UTC, azuchi commented on lib/glueby/internal/contract_builder.rb
> +
この３つのメソッドの追加って、`use_auto_fee`削除するのと関係あるんですか？

2023-05-08 17:28 UTC, Yamaguchi requested changes
`ContractBuilder`に`use_auto_fee`の実装が残っているのはTokenのIssueとtransfer以外の操作(タイムスタンプ？）に関してはこのオプション使い続けるという理解でOKか？

2023-05-09 02:47 UTC, rantan commented on lib/glueby/contract/token.rb
>          if token_metadata
`use_auto_fee` と `use_auto_fulfill_inputs` を併用しているものに関しては、次のPRで `use_auto_fee` オプションを削除する際に `use_auto_fulfill_inputs` だけが指定されるようにする予定です。

2023-05-09 02:51 UTC, rantan commented on lib/glueby/internal/contract_builder.rb
> +
issue で `use_auto_fulfill_inputs` を有効にするために必要な修正です。`use_auto_fee` の機能は `use_auto_fulfiff_inputs` と合体させる予定なので、`use_auto_fee` が有効で `use_auto_fulfill_inputs` が無効な設定はできなくなる予定です。そういった設定があると都合が悪いので、このPRで変更しています。

2023-05-09 02:53 UTC, rantan commented
> `ContractBuilder`に`use_auto_fee`の実装が残っているのはTokenのIssueとtransfer以外の操作(タイムスタンプ？）に関してはこのオプション使い続けるという理解でOKか？

use_auto_fee のオプションは次のPRで `use_auto_fulfill_inputs` に統合する予定です。なので、`use_auto_fee` オプションの指定は次のPRで削除します。

2023-05-09 05:10 UTC, rantan commented
> `token.rb`の213行目の
> 
> ```ruby
> # FIXME: It is enough to add just one UTXO here. Funding for fee should care by use_auto_fee feature. But, here add all UTXOs in issuer's wallet, if fee provider is enabled.
> ```
> 
> の説明への影響はありませんか・

次の PR で `use_auto_fee` オプションを削除する際に変更します。

2023-05-10 06:48 UTC, azuchi approved these changes

2023-05-10 17:03 UTC, Yamaguchi approved these changes

2023-05-11 04:41 UTC, merged