Fix duplicate inputs error
chaintope/glueby pull request #174
Opened 2023-05-10 12:30 UTC by rantan

This PR will fix below issue

When `#pay` of TPC is specified with both `use_auto_fee` and `use_auto_fulfill_inputs` enabled, both `auto_fee` and `auto_fulfill_inputs` try to set the UTXO of the TPC respectively, resulting in duplicate UTXOs may be set for both `auto_fee` and `auto_fulfill_inputs`.

2023-05-11 07:38 UTC, azuchi requested changes

2023-05-11 07:38 UTC, azuchi commented on lib/glueby/contract/token.rb
> +            # FIXME: It is enough to add just one UTXO here. But, here add all UTXOs in issuer's wallet, if fee provider is enabled.
このFIXMEの記述って合ってますか？↓だと複数のUTXO追加してるみたいだけど。

2023-05-11 07:38 UTC, azuchi commented on spec/glueby/contract/token_spec.rb
> +    let(:fee_estimator) { Glueby::Contract::FeeEstimator::Fixed.new(fixed_fee: 455) }
これはどうして変更してるんですか？あと変更したら、547行目のコメントの`Fee is 450 tapyrus`というのも変更が必要なのではなくて？

2023-05-11 07:38 UTC, azuchi commented on lib/glueby/internal/wallet.rb
> +        lock_utoxs = false,
```suggestion
        lock_utxos = false,
```

typo

2023-05-11 07:38 UTC, azuchi commented on lib/glueby/internal/wallet.rb
>        # - script_pubkey: [String] ScriptPubkey of the UTXO
@returnと@paramが合致してないようです。

2023-05-11 07:38 UTC, azuchi commented on lib/glueby/internal/wallet.rb
>        # - script_pubkey: [String] ScriptPubkey of the UTXO
@returnと@paramが合致してないようです。

2023-05-11 18:51 UTC, Yamaguchi requested changes

2023-05-11 18:51 UTC, Yamaguchi commented on lib/glueby/internal/wallet.rb
> +        excludes = nil
このメソッドの`excludes`パラメーターのデフォルトが`nil`で、`collect_colored_outputs`メソッドのデフォルトが空の配列になっているのですが、違いに意味ありますか？
特になければ空の配列に統一しても良いかと思います。

2023-05-14 10:24 UTC, Yamaguchi requested changes

2023-05-14 10:24 UTC, Yamaguchi commented on lib/glueby/internal/contract_builder.rb
> +          auto_fulfill_inputs_utxos_for_tpc(tx)
`auto_fulfill_inputs_utxos_for_tpc`というメソッドの中でお釣りの設定と署名までする必要があるか？
メソッド名の割に色々やってるなと思いました。

お釣りの設定は`add_change_for_tpc(tx)`でやるほうが良い。
署名は`sign(tx)`に集約できないか？

2023-05-15 05:43 UTC, rantan commented on spec/glueby/contract/token_spec.rb
> +    let(:fee_estimator) { Glueby::Contract::FeeEstimator::Fixed.new(fixed_fee: 455) }
変更している理由は、

> 1. output を dust output と判定する処理を TxOut#dust? に統一する
>   * DUST_LIMIT 定数と value を比較する処理がありましたが上に統一しました。

でdustと判定される基準が 600 tapyrus からこの場合 546 tapyrus に変わったためです。
コメントは修正が必要なので修正します。

2023-05-16 00:43 UTC, rantan commented on lib/glueby/contract/token.rb
> +            # FIXME: It is enough to add just one UTXO here. But, here add all UTXOs in issuer's wallet, if fee provider is enabled.
FeeProvider を使わない場合でも複数件の UTXO を追加する可能性がありますね。コメントにあるとおり、ここでは color_id を決定するために１つだけ UTXO を追加すればいい処理なので、そのように修正しました。 73dd890

2023-05-16 00:44 UTC, rantan commented on lib/glueby/internal/wallet.rb
> +        excludes = nil
[ee4b05f](https://github.com/chaintope/glueby/pull/174/commits/ee4b05fb7006d9ac1a78686ee962273c82c0664f) で修正しました。

2023-05-16 00:44 UTC, rantan commented on lib/glueby/internal/wallet.rb
>        # - script_pubkey: [String] ScriptPubkey of the UTXO
[ee4b05f](https://github.com/chaintope/glueby/pull/174/commits/ee4b05fb7006d9ac1a78686ee962273c82c0664f) で修正しました。

2023-05-16 00:44 UTC, rantan commented on lib/glueby/internal/wallet.rb
> +        lock_utoxs = false,
[ee4b05f](https://github.com/chaintope/glueby/pull/174/commits/ee4b05fb7006d9ac1a78686ee962273c82c0664f) で修正しました。

2023-05-16 00:44 UTC, rantan commented on spec/glueby/contract/token_spec.rb
> +    let(:fee_estimator) { Glueby::Contract::FeeEstimator::Fixed.new(fixed_fee: 455) }
[ee4b05f](https://github.com/chaintope/glueby/pull/174/commits/ee4b05fb7006d9ac1a78686ee962273c82c0664f) で修正しました。

2023-05-16 00:46 UTC, rantan commented on lib/glueby/internal/contract_builder.rb
> +        change_script = Tapyrus::Script.parse_from_addr(provider.change_address)
[f7a8094](https://github.com/chaintope/glueby/pull/174/commits/f7a8094b06d168959852758e3cd6d56ffd88a3d1) で修正しました。

add_change_for_tpc でおつりのアウトプットを追加するように集約したため、ここのおつりを追加する処理は消しました。

2023-05-16 00:46 UTC, rantan commented on lib/glueby/internal/contract_builder.rb
> +          auto_fulfill_inputs_utxos_for_tpc(tx)
[f7a8094](https://github.com/chaintope/glueby/pull/174/commits/f7a8094b06d168959852758e3cd6d56ffd88a3d1) で修正しました。

ご指摘のように集約しました！

2023-05-16 01:07 UTC, azuchi commented on lib/glueby/internal/wallet.rb
> +      # @return [Integer] The sum of return UTOXs
```suggestion
      # @return [Integer] The sum of return UTXOs
```

2023-05-16 01:07 UTC, azuchi commented on lib/glueby/internal/wallet.rb
> +      # @return [Integer] The sum of return UTOXs
```suggestion
      # @return [Integer] The sum of return UTXOs
```

2023-05-16 05:13 UTC, Yamaguchi approved these changes

2023-05-16 05:24 UTC, azuchi approved these changes

2023-05-16 05:24 UTC, merged