Build transaction using hex string option
chaintope/glueby pull request #181
Opened 2023-09-25 18:55 UTC by Yamaguchi

2023-09-26 05:54 UTC, rantan requested changes

2023-09-26 05:54 UTC, rantan commented on lib/generators/glueby/contract/templates/timestamp_table.rb.erb
> +      t.boolean  :hex, default: true
`null: false, default: false` がいいかと思いましたがいかがですか？
lib/glueby/contract/active_record/timestamp.rb の実装でも指定しなければ false になるようですし、デフォルトは false で問題ないかと思いました。

2023-09-26 05:54 UTC, rantan commented on lib/glueby/contract/active_record/timestamp.rb
> +        # - hex(optional) [Boolean]
`When the hex flag is true, the strings set in prefix and content are treated as hex strings.` みたいな説明があるとよいと思います。

2023-09-26 05:54 UTC, rantan commented on lib/glueby/contract/timestamp.rb
> +      # @param [Boolean] if true, prefix and content are treated as hex strings
```suggestion
      # @param [Boolean] hex If true, prefix and content are treated as hex strings
```

2023-09-26 14:34 UTC, Yamaguchi commented on lib/glueby/contract/timestamp.rb
> +      # @param [Boolean] if true, prefix and content are treated as hex strings
[2339222](https://github.com/chaintope/glueby/pull/181/commits/2339222dd13f29b2520de5f81ed66bbf7b3488ac)

2023-09-26 14:34 UTC, Yamaguchi commented on lib/glueby/contract/active_record/timestamp.rb
> +        # - hex(optional) [Boolean]
[2339222](https://github.com/chaintope/glueby/pull/181/commits/2339222dd13f29b2520de5f81ed66bbf7b3488ac)で修正しました

2023-09-26 14:34 UTC, Yamaguchi commented on lib/generators/glueby/contract/templates/timestamp_table.rb.erb
> +      t.boolean  :hex, default: true
[2339222](https://github.com/chaintope/glueby/pull/181/commits/2339222dd13f29b2520de5f81ed66bbf7b3488ac)修正しました。

2023-09-27 02:16 UTC, rantan approved these changes

2023-10-02 06:04 UTC, merged