Implement Glueby::Wallet#tokens
chaintope/glueby pull request #196
Opened 2023-11-03 04:32 UTC by Yamaguchi

This PR implements Glueby::Wallet#tokens to get token out_point(txid, index) and value.

2023-11-03 05:03 UTC, Yamaguchi commented
https://github.com/chaintope/tapyrus-api/issues/433

2023-11-09 02:26 UTC, rantan requested changes

2023-11-09 02:26 UTC, rantan commented on lib/glueby/internal/wallet.rb
> +      def tokens(color_id = Tapyrus::Color::ColorIdentifier.default, only_finalized = true)
`#collect_colored_outputs` と同じ処理に見えますが、そちらは使えませんか？
同じ処理が２つあるのはわかりにくいと思います。
性能的には `#tokens` の方が効率がよさそうですが。
性能が問題の場合は `#collect_colored_outputs` を改善する方が良いかと思いました。

2023-11-09 02:40 UTC, rantan commented on lib/glueby/internal/wallet.rb
> +      def tokens(color_id = Tapyrus::Color::ColorIdentifier.default, only_finalized = true)
`#tokens` を新設したのは、ページネーションできるようにするためですかね。
今の WalletAdapter の設計的には ActiveRecord::Base のサブクラスを ActiveRecordWalletAdapter の外まで引き回すのは良くないですね。やるなら下のどちらかがいいかと思いました。

* AbstractWalletAdapter を使った WalletAdapter の抽象化をやめる。
* WalletAdapter のインターフェースに `page`, `per` を加えて、内部でページネートさせる。

後者の方が影響が少なく良いと思いました。

2023-11-13 14:02 UTC, Yamaguchi commented on lib/glueby/internal/wallet.rb
> +      def tokens(color_id = Tapyrus::Color::ColorIdentifier.default, only_finalized = true)
page, perをパラメータに加えました。
e63b484723b1c6270a38d7e9d615f10be2e80d22

2023-11-13 14:15 UTC, Yamaguchi commented on lib/glueby/internal/wallet.rb
> +      def tokens(color_id = Tapyrus::Color::ColorIdentifier.default, only_finalized = true)
`Glueby::Internal::Wallet#collect_colored_outputs` は合計値を取得しているため、#tokensとは少し処理が違う認識です。

2023-11-21 01:56 UTC, rantan commented on lib/glueby/internal/wallet.rb
> +      def tokens(color_id = Tapyrus::Color::ColorIdentifier.default, only_finalized = true)
処理内容は合計値を無視すればいいだけなのでそんなに違わないかと思います。

`#collect_colored_outputs` にページネーションをつけようとすると、Kaminari が使えないのでいったん全件の UTXO を取得する必要があって、性能が悪くなるのは気になりますね。ページネーションに限らず `Gluby::Internal::Wallet::ActiveRecordWalletAdapter#list_unspent` を使っているところすべてにかかわる問題ですが。


Internal::Wallet に実装している、`#collect_uncolored_outputs`、`#collect_colored_outputs` 相当の機能を Wallet Adapter に入れて、もっと SQL で処理できるようにする方が良いかもしれませんね。本 PR とは別での対応になると思いますが。

2023-11-26 15:49 UTC, Yamaguchi commented on lib/glueby/internal/wallet.rb
> +      def tokens(color_id = Tapyrus::Color::ColorIdentifier.default, only_finalized = true)
8c01bba11e24f3036412db713d2ae9a3ba3ed925 で `ActiveRecordWalletAdapter#list_unspent` 内で`#tokens`メソッドを使用するように修正しました。

2023-11-28 02:59 UTC, rantan commented on lib/glueby/internal/wallet.rb
> +      def tokens(color_id = Tapyrus::Color::ColorIdentifier.default, only_finalized = true)
2点まとめて書きます。

color_id カラムを追加していますが、マイグレーション処理は glueby を使用しているアプリケーション側で実装する想定でしょうか？

`#tokens` という名前は実装と合わないので変えた方が良いと思いますが、、`#list_unspent` がすでに使われているので、悩ましいですね。`#list_unspent_inner` のような名前で private メソッドにしてしまって、外部からは `#list_unspent` を呼び出す形で統一するのではどうでしょうか？

2023-11-28 03:11 UTC, rantan requested changes

2023-11-28 03:11 UTC, rantan commented on lib/glueby/wallet.rb
> +    def tokens(color_id = nil, only_finalized = true, page = 1, per = 25)
`#token_utxos`  はどうでしょうか？実際に返しているのは UTXO なので。

2023-11-28 03:11 UTC, rantan commented on lib/glueby/contract/tx_builder.rb
>          sum_token, outputs = collect_colored_outputs(utxos, color_id, amount)
`#collect_colored_outputs` 側も修正が必要かと思いましたが、tx_builder 時代非推奨で、ほとんど使用していないので、多少余計な処理が残ってしまっていても、そのままでいいかと思いました。

2023-11-28 03:11 UTC, rantan commented on lib/glueby/internal/wallet/active_record/wallet.rb
> +          def tokens(color_id = Tapyrus::Color::ColorIdentifier.default)
このメソッドは使われていなさそうです。

2023-11-28 03:11 UTC, rantan commented on lib/glueby/internal/wallet/active_record_wallet_adapter.rb
> +        def tokens(wallet_id, color_id = nil, only_finalized = true, page = 1, per = 25)
`#tokens` という名前は実装と合わないので変えた方が良いと思いますが、`#list_unspent` がすでに使われているので、悩ましいですね。`#list_unspent_inner` のような名前で private メソッドにしてしまって、Wallet Adapter の 外部からは `#list_unspent` を呼び出す形で統一するのではどうでしょうか？

2023-11-28 03:11 UTC, rantan commented on lib/glueby/internal/wallet/active_record_wallet_adapter.rb
> +        def tokens(wallet_id, color_id = nil, only_finalized = true, page = 1, per = 25)
その場合、件数を取得できないので、件数を返すインターフェースを新しく作るのはどうでしょうか？
`#list_unspent_count` みたいな名前で。内部では `#list_unspent_inner.count` をページネーションパラメーターを与えずに実行するイメージです。

2023-11-28 05:06 UTC, Yamaguchi commented on lib/glueby/internal/wallet.rb
> +      def tokens(color_id = Tapyrus::Color::ColorIdentifier.default, only_finalized = true)
そうです。

2023-11-29 06:53 UTC, Yamaguchi commented on lib/glueby/wallet.rb
> +    def tokens(color_id = nil, only_finalized = true, page = 1, per = 25)
6056b0fb9f9a4d664a498b6a54c9157b7c59e2f8 でリネームしました

2023-11-29 07:22 UTC, Yamaguchi commented on lib/glueby/internal/wallet/active_record/wallet.rb
> +          def tokens(color_id = Tapyrus::Color::ColorIdentifier.default)
削除しました(d01e3fc942c055ee42c5115db2817616baa88c4c)

2023-11-29 10:00 UTC, Yamaguchi commented on lib/glueby/internal/wallet/active_record_wallet_adapter.rb
> +        def tokens(wallet_id, color_id = nil, only_finalized = true, page = 1, per = 25)
影響範囲広いですけど、現状の
```ruby
def list_unspent(wallet_id, color_id = nil, only_finalized = true, label = nil)
...
end
```

のインターフェースを

```ruby
def list_unspent(wallet_id, color_id = nil, only_finalized = true, label = nil, page = 1, per = 0)
...
end
```

に変更するのはどうでしょうか。per=0のときはページングしないという動作で。
「件数を返すインターフェース」というのが具体的にどのようなものなのか理解できてないです。

2023-11-30 04:44 UTC, Yamaguchi commented on lib/glueby/internal/wallet/active_record_wallet_adapter.rb
> +        def tokens(wallet_id, color_id = nil, only_finalized = true, page = 1, per = 25)
> `#list_unspent_inner` のような名前で private メソッドにしてしまって、Wallet Adapter の 外部からは `#list_unspent` を呼び出す形で統一するのではどうでしょうか？

これの意味が理解できていませんが、
現状のlist_unspentとは別に件数も含めて返すlist_unspent_with_countみたいなメソッド名にするという認識であってますか？

```ruby

def list_unspent(wallet_id, only_finalized = true, label = nil)
   ...
end

def list_unspent_with_count(wallet_id, only_finalized = true, label = nil, page = 1, per = 25)
    ...
    {
        count: 件数,
        outputs:`1ページ分の結果`
    }
end
```

2023-11-30 05:38 UTC, Yamaguchi commented on lib/glueby/internal/wallet/active_record_wallet_adapter.rb
> +        def tokens(wallet_id, color_id = nil, only_finalized = true, page = 1, per = 25)
213e661e8e27cb737ef56ae8a5a942a26fc059a1 で上記対応しました

2023-11-30 06:32 UTC, rantan commented on lib/glueby/internal/wallet/active_record_wallet_adapter.rb
> +        def tokens(wallet_id, color_id = nil, only_finalized = true, page = 1, per = 25)
引数にマッチするUTXOの件数だけを返すメソッドを追加するのはどうかと言う話でした。それで、list_unspent にページネーション用のパラメーターを加えると、UTXOのリストはlist_unspentで取得し、全体の件数は追加するメソッドで取得できると考えました。

たた、いまの list_unspent_with_count は名前からlistunspentの使い分けも分かりますし、良いと思います。

2023-12-01 03:03 UTC, rantan requested changes

2023-12-01 05:59 UTC, Yamaguchi commented on lib/glueby/internal/wallet.rb
> +      def list_unspent(color_id = nil, only_finalized = true, label = :unlabeled)
他のパラメータがデフォルト値付きの引数だったので、それに倣いましたが、確かに既存への影響ないので、キーワード引数で良いですね。

555608c9cb1a85d266ce2622b7a4a0dc33713cd2 で修正してます

2023-12-01 05:59 UTC, Yamaguchi commented on lib/glueby/internal/wallet/abstract_wallet_adapter.rb
> +        def list_unspent(wallet_id, color_id = nil, only_finalized = true, label = nil)
555608c9cb1a85d266ce2622b7a4a0dc33713cd2 で修正してます

2023-12-01 08:23 UTC, rantan approved these changes

2023-12-05 06:13 UTC, merged