Add version column to Timestamp table
chaintope/glueby pull request #200
Opened 2024-01-10 05:24 UTC by Yamaguchi

2024-01-10 06:36 UTC, rantan commented
Timestampモジュールの最上位あたりに、バージョニングの説明と各バージョンの挙動の差分が説明されたコメントが欲しいです。

2024-01-10 06:36 UTC, rantan commented on lib/generators/glueby/contract/templates/timestamp_table.rb.erb
>        t.boolean  :hex, null: false, default: false
hexフラグは不要 by @azuchi

2024-01-10 06:37 UTC, rantan commented on lib/glueby/contract/active_record/timestamp.rb
> +            version: attributes[:version] || "1"
```suggestion
            version: attributes[:version] || "2"
```

はどうでしょう？

2024-01-10 06:39 UTC, rantan commented on lib/glueby/contract/active_record/timestamp.rb
> +            version: attributes[:version] || "1"
デフォルト値は不要 by @azuchi

2024-01-11 05:36 UTC, Yamaguchi commented
> Timestampモジュールの最上位あたりに、バージョニングの説明と各バージョンの挙動の差分が説明されたコメントが欲しいです。

`lib/glueby/contract/timestamp.rb` のTimestampクラスに説明を追記してます。

2024-01-11 08:10 UTC, Yamaguchi commented on lib/glueby/contract/active_record/timestamp.rb
> +            version: attributes[:version] || "1"
67c0415e188342f3cd5c7902135ceb7bf7662cf1 で修正してます

2024-01-11 08:11 UTC, Yamaguchi commented on lib/generators/glueby/contract/templates/timestamp_table.rb.erb
>        t.boolean  :hex, null: false, default: false
67c0415e188342f3cd5c7902135ceb7bf7662cf1 で削除してます

2024-01-12 05:05 UTC, azuchi commented on lib/glueby/contract/timestamp.rb
> +        @version = version
現在、`1`と`2`のみをサポートしているので、それ以外が指定されていないかチェックする必要があるかと思います。

2024-01-12 05:05 UTC, azuchi commented on lib/glueby/contract/timestamp.rb
> +        version: nil
```suggestion
        version:
```

で良いのでは？

2024-01-12 05:34 UTC, Yamaguchi commented on lib/glueby/contract/timestamp.rb
> +        @version = version
バリデーションを追加しました。bea501b8bd91ab44eadf4242887b96485d38b94b

2024-01-12 05:34 UTC, Yamaguchi commented on lib/glueby/contract/timestamp.rb
> +        version: nil
bea501b8bd91ab44eadf4242887b96485d38b94b で修正しました。

2024-01-12 05:43 UTC, azuchi approved these changes

2024-01-12 07:09 UTC, rantan requested changes

2024-01-16 05:34 UTC, rantan commented on lib/glueby/contract/active_record/timestamp.rb
> +        #     Version "2" treats the specified content and prefix as a hexadecimal string with the string set to prefix and content.
バリデーションでチェックしているようですね。

2024-01-16 05:34 UTC, rantan approved these changes

2024-01-17 04:11 UTC, merged