add sync_block rake task
chaintope/glueby pull request #41
Opened 2021-03-18 02:20 UTC by oshikawatkm

This PR is for Adding Block Sync Rake Task.
When You execute `bin/rails glueby:contract:wallet_adapter:sync_block`, glueby import blocks and txs.

2021-03-18 02:50 UTC, azuchi requested changes
BlockSyncerというTaskを別に作成し、そのブロックの同期処理から、TimestampやPaymentの処理の同期タスクを呼び出すようにしましょう。

2021-03-18 02:50 UTC, azuchi commented on lib/generators/glueby/contract/templates/block_table.rb.erb
> +class CreateBlock < ActiveRecord::Migration<%= migration_version %>
他にも今後、こういったデータは出てきそうなので、`SystemInformation`にして、key, value（両方String）のテーブルにしましょう。
あと、created_at、updated_atも追加で。

2021-03-18 02:50 UTC, azuchi commented on lib/tasks/glueby/contract/wallet_adapter.rake
> +            for i in saved_block.synced_block_number..latest_block_num do
```suggestion
            (saved_block.synced_block_number..latest_block_num).each do |i|
```

2021-03-18 02:50 UTC, azuchi commented on lib/tasks/glueby/contract/wallet_adapter.rake
> +          rescue
何のための`rescue`?

2021-03-18 02:50 UTC, azuchi commented on lib/tasks/glueby/contract/timestamp.rake
> +
`wallet_adapter.rake`と同じtaskになってます。
ここで必要なのは、Timestampのブロックの同期に伴うTimestampの更新です。

2021-03-18 02:50 UTC, azuchi commented on lib/tasks/glueby/contract/wallet_adapter.rake
> +            saved_block.update(synced_block_number: i)
上記のforの各ループ単位でDBのトランザクション境界を切ることで、この更新は不要になります。

2021-03-18 04:20 UTC, oshikawatkm commented on lib/tasks/glueby/contract/wallet_adapter.rake
> +          rescue
sync_blockメソッドでは最初から最新のブロックまで全てのblockに対してimport_blockメソッドとimport_txメソッドを呼んでいるのですが、import_txメソッドは自分宛でないtxを引数に取るとエラーが起き、sync_blockメソッドが止まってしまうのでrescueを追加し回避しました。
自分宛のTxかどうかをチェックする処理をimport_txメソッドに追加するなどをするべきでした。

2021-03-18 04:46 UTC, azuchi commented on lib/tasks/glueby/contract/wallet_adapter.rake
> +          rescue
具体的にどこで、何のエラーが発生していますか？

2021-03-18 05:10 UTC, oshikawatkm commented on lib/tasks/glueby/contract/wallet_adapter.rake
> +          rescue
import_txメソッドの一行目、`RPC.client.getrawtransaction`でノードから"No such mempool transaction."のメッセージが返ってくることにより、エラーが発生します。

2021-03-18 05:23 UTC, azuchi commented on lib/tasks/glueby/contract/wallet_adapter.rake
> +          rescue
正確には `"No such mempool transaction. Use -txindex to enable blockchain transaction queries"`では？
これは、Tapyrus Coreの `-txindex`オプションが有効になっていないからですね。このオプションを有効するよう設定ファイルを変更するとエラーは発生しなくなります。

2021-03-19 09:19 UTC, azuchi requested changes

2021-03-19 09:19 UTC, azuchi commented on spec/tasks/glueby/contract/wallet_adapter_spec.rb
> +  setup_responses
突然のメソッド呼び出しのようになっているので、`setup_responses`の内容を`shared_context`で定義して、利用するテストケースで`include_context`するのが良いかと思います。

2021-03-19 09:19 UTC, azuchi commented on lib/glueby/internal/wallet/active_record/system_information.rb
> +        end
```ruby
def self.synced_block_height
...
end
```
というメソッド作るのが良いと思います。

2021-03-19 09:19 UTC, azuchi commented on spec/tasks/glueby/contract/block_syncer_spec.rb
> +      expect(Glueby::Internal::Wallet::AR::SystemInformation.find(1)).not_to be_nil
`nil`じゃなくて、期待するブロック高を検証すべきです。

2021-03-19 09:19 UTC, azuchi commented on spec/tasks/glueby/contract/block_syncer_spec.rb
> +    it { expect { subject }.to change { Glueby::Internal::Wallet::AR::Utxo.count }.from(1).to(2) }
この`it`の内容は↑と分ける必要は無いのでは？

2021-03-19 09:19 UTC, azuchi commented on lib/tasks/glueby/contract/block_syncer.rake
> +        Glueby::Contract::Task::Timestamp.confirm
よくみると、Timestampはブロックの承認ではなくTxを直接確認してるようなので、BlockSyncerからは外しますか。

2021-03-23 03:06 UTC, oshikawatkm commented on spec/tasks/glueby/contract/block_syncer_spec.rb
> +    it { expect { subject }.to change { Glueby::Internal::Wallet::AR::Utxo.count }.from(1).to(2) }
subjectが二回実行されることにより、Utxoのレコード数が多くなってしまうのを防ぐために、`it`で分けています。

2021-03-23 04:47 UTC, azuchi commented on spec/tasks/glueby/contract/block_syncer_spec.rb
> +    it { expect { subject }.to change { Glueby::Internal::Wallet::AR::Utxo.count }.from(1).to(2) }
`subject`は`it`の個数分、実行されるので、↑だといずれにしても2回実行されます。

2021-03-23 04:54 UTC, azuchi commented on spec/tasks/glueby/contract/block_syncer_spec.rb
> +    it { expect { subject }.to change { Glueby::Internal::Wallet::AR::Utxo.count }.from(1).to(2) }
2回実行されるのは`it`を分けるからではなく、`it`の中で`expect { subject }`を2回呼んだからでしょう。以下のように修正することで`it`は１つにできます。

```ruby
describe '#start' do
    subject { Rake.application['glueby:contract:block_syncer:start'] }

    it do
      expect(rpc).to receive(:getblockcount).once
      expect(rpc).to receive(:getblock).twice
      expect(rpc).to receive(:getblockhash).twice
      expect(rpc).to receive(:getrawtransaction).exactly(4).times
      expect(Glueby::AR::SystemInformation.synced_block_height).to eq(1)
      expect(Glueby::Internal::Wallet::AR::Utxo.count).to eq(1)
      subject.invoke
      expect(Glueby::AR::SystemInformation.synced_block_height).to eq(2)
      expect(Glueby::Internal::Wallet::AR::Utxo.count).to eq(2)
    end
  end
  ```

2021-03-23 05:42 UTC, oshikawatkm commented on spec/tasks/glueby/contract/block_syncer_spec.rb
> +    it { expect { subject }.to change { Glueby::Internal::Wallet::AR::Utxo.count }.from(1).to(2) }
そちらの方法で修正しました。

2021-03-23 06:21 UTC, azuchi requested changes

2021-03-23 06:21 UTC, azuchi commented on lib/glueby/active_record/system_information.rb
> +        @synced_block_height = SystemInformation.find_by(info_key: "synced_block_number").info_value.to_i
値ではなく、`SystemInformation`自体を返しましょう。そすると、`BlockSyncer`の`Glueby::AR::SystemInformation.find_by(info_key: "synced_block_number")`もこのメソッドに置き換えられます。

2021-03-23 07:10 UTC, azuchi requested changes

2021-03-23 07:10 UTC, azuchi commented on lib/tasks/glueby/contract/block_syncer.rake
> +            ::ActiveRecord::Base.transaction do
`synced_block.info_value.to_i + 1` から処理しないと、次回実行時、前回処理したブロクを再度実行することになるのでは？

2021-03-23 07:10 UTC, azuchi commented on lib/tasks/glueby/contract/block_syncer.rake
> +          (synced_block.info_value.to_i..latest_block_num).each do |i|
`info_value.to_i`するのが冗長的なので、`SystemInformation#int_value`なメソッドがあってもいいかと思いました。

2021-03-23 09:11 UTC, azuchi approved these changes

2021-03-23 09:11 UTC, merged