fix list_unspent to get all unlabeled utxo
chaintope/glueby pull request #76
Opened 2021-08-04 05:32 UTC by bonn1112

This PR fixes the list_unspent method to get all unlabeled utxos by specifying ":unlabeled" as argument below.

```ruby
wallet.list_unspent(true, :unlabeled)
```

2021-08-04 08:49 UTC, Yamaguchi commented on lib/glueby/internal/wallet/active_record_wallet_adapter.rb
> +          key = wallet.keys.create(purpose: :receive, label: label || nil)
変更前の ```label || '' ``` の意味は「labelがnilだったら代わりに''(空文字)を使う」なので、
「labelがnilだったらそのままnilを使う」のであれば、``` label || nil ``` ではなく単に``` label ```だけでも同じ動作(nil)になると思いますがいかがでしょうか。

2021-08-05 04:26 UTC, Yamaguchi commented
TapyrusCoreWalletAdapterへの変更は不要でしょうか。

https://github.com/chaintope/glueby/blob/master/lib/glueby/internal/wallet/tapyrus_core_wallet_adapter.rb

2021-08-05 04:28 UTC, Yamaguchi requested changes
TapyrusCoreWalletAdapterへの変更は不要でしょうか。

https://github.com/chaintope/glueby/blob/master/lib/glueby/internal/wallet/tapyrus_core_wallet_adapter.rb

2021-08-05 04:39 UTC, Yamaguchi commented
一応確認のために書きます。認識違ってたら訂正してください。

元々の問題は

1. labelが設定されていないアドレスへコインを送る。
2. labelが設定されている(Glueby-Contract-Tracking)アドレスにもコインを送る。
3. その後、list_unspentを使ってコインを検索したい。

- すべてのコイン(1と2)を抽出する場合はlabel = nilを指定するとよい。list_unspent(label = nil)
- 設定されているコイン(2)を抽出する場合はlabel = 'Glueby-Contract-Tracking'を指定するとよい。list_unspent(label ='Glueby-Contract-Tracking')
- labelが設定されていないコイン(1)のみを抽出したい場合は現状list_unspentだけではできない。

なので
「list_unspoentの仕様を変更して、list_unspent(label = 'unlabeled')を指定して、検索できるようにしたい。」
が今回のRPの内容。

2021-08-05 04:50 UTC, Yamaguchi reviewed
https://github.com/chaintope/glueby/blob/master/lib/glueby/internal/wallet.rb#L85

ここらへんにlabelで指定するものに対する説明を追加してくれると嬉しい。細かい文章はお任せしますが。

@param label [String] キーまたはUtxoがラベル付けされている場合にそのラベルで結果の絞り込みを行う。labelが指定されない(label=nil)だとすべてを返す。label=:unlabeledだとlabelされていないものだけを返す。

2021-08-05 05:54 UTC, bonn1112 commented
@Yamaguchi 
同じ認識でいると思います。

元の問題では1 を取り出す際に、`label=nil`と`label=''`の2種類が存在していたため、#list_unspent ですべての UTXO を取得したあとに、 空文字 と nil でフィルターする必要がありました。

このPRの目的は「`label=''`を廃止し、1のコインのみを取り出す際は`(label = 'unlabeled')`を指定して検索する。」で認識あっていると思います。

> 一応確認のために書きます。認識違ってたら訂正してください。
> 
> 元々の問題は
> 
> 1. labelが設定されていないアドレスへコインを送る。
> 2. labelが設定されている(Glueby-Contract-Tracking)アドレスにもコインを送る。
> 3. その後、list_unspentを使ってコインを検索したい。
> 
> * すべてのコイン(1と2)を抽出する場合はlabel = nilを指定するとよい。list_unspent(label = nil)
> * 設定されているコイン(2)を抽出する場合はlabel = 'Glueby-Contract-Tracking'を指定するとよい。list_unspent(label ='Glueby-Contract-Tracking')
> * labelが設定されていないコイン(1)のみを抽出したい場合は現状list_unspentだけではできない。
> 
> なので
> 「list_unspoentの仕様を変更して、list_unspent(label = 'unlabeled')を指定して、検索できるようにしたい。」
> が今回のPRの内容。

2021-08-05 11:20 UTC, Yamaguchi commented
> TapyrusCoreWalletAdapterへの変更は不要でしょうか。
> 
> https://github.com/chaintope/glueby/blob/master/lib/glueby/internal/wallet/tapyrus_core_wallet_adapter.rb

https://chainquery.com/bitcoin-cli/listunspent

もともと、RPCのインターフェースとしてはラベルで絞り込むことはできないので、現在の実装のように全部取ってきてfilterするしかないのですが、label = :unlabeledが指定された時だけ、label = ""の条件で絞り込む必要がありそうです。
(現状だとアドレスのラベルが"unlabeled"という文字列のものが抽出されるはず)

https://github.com/chaintope/glueby/blob/master/lib/glueby/internal/wallet/tapyrus_core_wallet_adapter.rb#L91

2021-08-12 03:24 UTC, bonn1112 commented
@Yamaguchi 

TapyrusCoreWalletAdapterで、`label = :unlabeled`が指定された際、`label=nil`のutxoのみを取得するように修正しました。

2021-08-12 06:57 UTC, merged