add only finalized option for collect_uncolored_outputs method
chaintope/glueby pull request #82
Opened 2021-08-23 07:33 UTC by bonn1112

When setting the utxo for fee, etc., it is now possible to specify the status of the utxo to be retrieved as an option, as shown below.

手数料のためのutxoセットするなどの際、以下のように取得するutxoのstatusをオプションで指定できるようにしました。

```ruby
_, outputs = wallet.internal_wallet.(fee, true, :unlabeled)
```

2021-08-23 23:13 UTC, rantan requested changes

2021-08-23 23:13 UTC, rantan commented on lib/glueby/internal/wallet.rb
> +      def collect_uncolored_outputs(amount, only_finalized = true, label = nil)
`only_finalized` は `label` の後ろに追加したほうが、既存の利用箇所への影響を最小限に出来るので良いと思います。

2021-08-24 04:35 UTC, rantan requested changes

2021-08-24 04:35 UTC, rantan commented on spec/glueby/internal/wallet_spec.rb
> +    subject { wallet.internal_wallet.collect_uncolored_outputs(amount, only_finalized) }
第２引数に only_finalized を渡していますが、第３引数で渡す必要があると思います。

2021-08-24 04:35 UTC, rantan commented on spec/glueby/internal/wallet_spec.rb
> +    context 'with unconfirmed' do
テストの書き方を修正する必要があります。

`#list_unspent` が返す UTXO のセットをstubしているので、`#list_unspent` の引数に only_finalzed を渡しても結果には影響しません。実際、`let(:only_finalized) { true }` としてテストを実行しても、テストをパスすると思います。

どう修正すればいいかですが、

* finalizedされた UTXO のセットを用意し、それをつかう
* only_finalized: false で `#list_unspent` が呼ばれることを検証する。

という方針でいいかと思います。

```ruby
it do
        expect(internal_wallet).to receive(:list_unspent).with(false, nil).and_return(unspents)
        expect(subject[0]).to eq 250_000_000
      end
```

2021-08-24 05:39 UTC, bonn1112 commented on spec/glueby/internal/wallet_spec.rb
> +    context 'with unconfirmed' do
ありがとうございます。
only_finalized: false の`#list_unspent`が呼ばれることを検証すればよかったですね。修正しました。

2021-08-25 00:47 UTC, rantan commented on spec/glueby/internal/wallet_spec.rb
>      it { expect(subject[0]).to eq 200_000_000 }
ここのテストおかしいですね。 only_finalized が true なのに、 false の UTXO を取得している様に見えます。
今回手を入れた場所ではないですが、 `let(:only_finalized) { true }` のときは、unspents が `finalized :true` のものだけを返すように修正してもらえませんか？
このテストの金額も 150_000_000 になると思います。

2021-08-25 04:18 UTC, bonn1112 commented
気づきませんでした。ありがとうございます。
`finalized=true`のみのunspentsを追加し、塞いでいる返り値を分けるようにしてみました。

2021-08-30 16:07 UTC, rantan requested changes
対応ありがとうございます。細かい点１点だけコメントしています。

2021-08-30 16:07 UTC, rantan commented on spec/glueby/internal/wallet_spec.rb
> +    let(:finalized_unspents) do
unspents との差が、 finalized: false のものを除外しただけであれば、以下のような書き方で良いと思います。

```ruby
unspents.select{|i| i[:finalized]}
```

2021-09-01 01:22 UTC, bonn1112 commented on spec/glueby/internal/wallet_spec.rb
> +    let(:finalized_unspents) do
ありがとうございます。早速修正しています。

2021-09-01 02:06 UTC, merged