Change default list_unspent to protect labeled UTXOs
chaintope/glueby pull request #92
Opened 2021-10-26 05:46 UTC by bonn1112

Change `Glueby::Internal::Wallet#list_unspent`(collecting UTXOs functions) into getting unlabelled UTXOs by default to prevent labeled UTXOs from consuming for other purposes.

Fix #84

2021-11-04 02:45 UTC, rantan requested changes
Can you add functionality tests for :unlabeled and :all features. Especially I wandor if the case of tapyrus core wallet.

2021-11-04 02:45 UTC, rantan commented on lib/glueby/internal/wallet.rb
>        end
The label default value should be `:unlabeled`.
And also the label variable should be set :unlabeled if the label argument is nil.

```suggestion
      #                    - If label is nil or :unlabeled, only unlabeled UTXOs will be returned.
      #                    - If label=:all, all UTXOs will be returned.
      def list_unspent(only_finalized = true, label = :unlabeled)
        label = :unlabeled unless label
        wallet_adapter.list_unspent(id, only_finalized, label)
      end
```

2021-11-04 02:45 UTC, rantan commented on lib/glueby/internal/wallet/active_record_wallet_adapter.rb
> +        # If label=:all, it will return all utxos
Method documentation should be placed at `abstract_wallet_adapter.rb` where declares interfaces.

2021-11-04 02:45 UTC, rantan commented on lib/glueby/internal/wallet/active_record_wallet_adapter.rb
> +        # If label=:all, it will return all utxos
Here should describe :unlabeled. It can be passed.

2021-11-17 02:34 UTC, rantan requested changes

2021-11-17 02:34 UTC, rantan commented on spec/functional/payment_spec.rb
> +        )
ここも、UTXOデータを直接作るのではなく、送金処理を実行して UTXO を作ってください。

2021-11-17 02:34 UTC, rantan commented on spec/functional/timestamp_spec.rb
> +        )
ここも、UTXOデータを直接作るのではなく、送金処理を実行して UTXO を作ってください。

2021-11-17 02:34 UTC, rantan commented on spec/functional/timestamp_spec.rb
> +        )
ここも、UTXOデータを直接作るのではなく、送金処理を実行して UTXO を作ってください。

2021-11-17 02:34 UTC, rantan commented on spec/functional/token_spec.rb
> +        )
ここも、UTXOデータを直接作るのではなく、送金処理を実行して UTXO を作ってください。

2021-11-17 02:34 UTC, rantan commented on spec/functional/token_spec.rb
> +        )
ここも、UTXOデータを直接作るのではなく、送金処理を実行して UTXO を作ってください。

2021-11-18 05:11 UTC, bonn1112 commented
@rantan 

ラベル付きのutxoのamountをテストする際、以下のように固定値で検証する以外方法が思い浮かびませんでした。`before_balance`メソッドなどを利用したほうがより読みやすくなるのかなとは思ったのですが、もし何かもっといい方法ありましたら教えていただきたいです。

```ruby
 expect(receiver.internal_wallet.list_unspent(false, 'labeled')[0][:amount]).to eq(5_000_000_000)
```

2021-11-24 02:56 UTC, rantan requested changes

2021-11-24 02:56 UTC, rantan commented on spec/functional/payment_spec.rb
> +        process_block(to_address: receiver.internal_wallet.receive_address('labeled'))
ここは `receiver` じゃなくて `sender` ですよね？

2021-11-24 02:56 UTC, rantan commented on spec/functional/payment_spec.rb
>      context 'bear fees by sender' do
ラベル付きの UTXO をつくって、それが消費されないことを検証するテストになっていますが、実際には送金額は残高に対して十分小さいので、もともとラベル付きの UTXO を消費する必要がなく、今回の修正を外してもパスするテストになっていると思います。

ラベルつきのUTXOしかない状態で、送金を試み、資金不足で失敗することを検証するというのはどうでしょうか？

```ruby
    context 'bear fees by sender' do
      let!(:sender) { Glueby::Wallet.create }
      let!(:receiver) { Glueby::Wallet.create }
      let(:before_balance) { sender.balances(false)[''] }
      let(:fee) { 10_000 }
      let(:fee_estimator) { Glueby::Contract::FixedFeeEstimator.new(fixed_fee: fee) }

      it 'pays TPC to another wallet' do
        # create labeled utxo
        process_block(to_address: sender.internal_wallet.receive_address('labeled'))

        expect do
          Glueby::Contract::Payment.transfer(
            sender: sender,
            receiver_address: receiver.internal_wallet.receive_address,
            amount: 10_000,
            fee_estimator: fee_estimator
          )
        end.to raise_error(Glueby::Contract::Errors::InsufficientFunds)

        # should not consume 'labeled' utxos
        expect(sender.internal_wallet.list_unspent(false, 'labeled').size).to eq(1)
        expect(sender.internal_wallet.list_unspent(false, 'labeled')[0][:amount]).to eq(5_000_000_000)

        # create a usable utxo for payment
        process_block(to_address: sender.internal_wallet.receive_address)
        before_balance

        Glueby::Contract::Payment.transfer(
          sender: sender,
          receiver_address: receiver.internal_wallet.receive_address,
          amount: 10_000,
          fee_estimator: fee_estimator
        )

        # sender lose sent amount and fee
        expect(sender.balances(false)['']).to eq(before_balance - (10_000 + fee))
        # receiver got the sent amount
        expect(receiver.balances(false)['']).to eq(10_000)
        # should not consume 'labeled' utxos
        expect(sender.internal_wallet.list_unspent(false, 'labeled').size).to eq(1)
        expect(sender.internal_wallet.list_unspent(false, 'labeled')[0][:amount]).to eq(5_000_000_000)
      end
    end
```

2021-11-24 02:56 UTC, rantan commented on spec/functional/payment_spec.rb
>      context 'bear fees by sender' do
ほかの機能テストについても同様のテストがあることが望ましいですが、時間も惜しくなってきたので、この機能の機能テストは payment_spec.rb だけにして、ほかの機能テストからは消しても良いかと思いました。
機能することは確認出来ているので。

どうですか？

2021-11-24 03:24 UTC, bonn1112 commented on spec/functional/payment_spec.rb
> +        process_block(to_address: receiver.internal_wallet.receive_address('labeled'))
すみません`sender`ですね。修正します。

2021-11-24 03:41 UTC, bonn1112 commented on spec/functional/payment_spec.rb
>      context 'bear fees by sender' do
@rantan 

コードありがとうございます。勉強になります。payment_spec.rbのみに頂いたテスト反映させました。

2021-11-24 04:17 UTC, merged