Implement Utxo provider for Timestamp feature
chaintope/glueby pull request #93
Opened 2021-11-08 05:27 UTC by Yamaguchi

This PR implements UTXO Provider proposed in https://github.com/chaintope/glueby/issues/87
, and apply it to the timestamp feature.

2021-11-15 07:17 UTC, azuchi requested changes
`README.md`に追加したconfigurationの説明を追記してください。

2021-11-15 07:17 UTC, azuchi commented on lib/tasks/glueby/contract/timestamp.rake
> +                ::ActiveRecord::Base.transaction { wallet.internal_wallet.broadcast(funding_tx) }
`funding_tx`をブロードキャストした件、ログ出力しておいた方がいいかと思います。

2021-11-15 07:36 UTC, azuchi commented on lib/glueby/utxo_provider.rb
> +      sum, outputs = wallet.collect_uncolored_outputs(fee + value)
`get_utxo`自体は後でトランザクションをブロードキャストするため、それまでのタイムラグを考えると同じUTXOを消費しようとしてエラーになるケースが考えられます。この対応には、

* UTXOの取得を`syncrorized`的にロックする
* UTXOを確率的に選択する

が考えられますが、実際にブロードキャストされるのが後になると現実的には後者の対応が必要ではないでしょうか？

2021-11-18 05:29 UTC, Yamaguchi commented on lib/glueby/utxo_provider.rb
> +    # @return [Integer] The output index in the tx to indicate the place of a provided UTXO.
https://www.rubydoc.info/gems/yard/file/docs/Tags.md#order-dependent-lists

を参考にして、 `@return [Array<(Tapyrus::Tx, Integer)>]` と修正しました。

2021-11-18 07:50 UTC, Yamaguchi commented on lib/glueby/utxo_provider.rb
> +      sum, outputs = wallet.collect_uncolored_outputs(fee + value)
`Glueby::Internal::Wallet#collect_uncolored_outputs` にシャッフルして返すためのオプションを追加しました。

2021-11-18 08:33 UTC, azuchi approved these changes

2021-11-18 08:33 UTC, merged