Rake tasks to maintain utxo pool.
chaintope/glueby pull request #94
Opened 2021-11-09 08:03 UTC by Yamaguchi

Implement rake tasks that maintain utxo pool in UtxoProvider wallet.

2021-11-15 08:02 UTC, azuchi requested changes
追加したrakeタスクについて、README.mdに追記してください。

2021-11-15 08:02 UTC, azuchi commented on lib/glueby/utxo_provider/tasks.rb
> +        shortage = [utxo_provider.utxo_pool_size - current_utxo_pool_size, 0].max
`utxo_pool_size`の設定値によっては、TapyrusのTxサイズのポリシーに違反する可能性があるため、別途上限を設けた方が良いかと思います。

2021-11-18 14:22 UTC, Yamaguchi commented on lib/glueby/utxo_provider/tasks.rb
> +        shortage = [utxo_provider.utxo_pool_size - current_utxo_pool_size, 0].max
utxo_pool_sizeの設定上限は2000個にしようかと思いますが、どうでしょうか。

Txサイズの最大値は100kb(https://github.com/chaintope/tapyrus-core/blob/master/src/policy/policy.h#L25)
input が数個、outputsが2000個のTxの場合には70kb程度となります。(https://bitcoinops.org/en/tools/calc-size/ で計算)

fee_providerにも同様の制限を追加します。
(28f50880ac3279cc6ea23842ca2a1137a82cfb13)

2021-11-18 14:22 UTC, Yamaguchi commented on lib/glueby/utxo_provider/tasks.rb
> +        puts wallet.receive_address
32957e4a586d5e8c3f27b7d3ddcdf27786da93e8 で修正しました。

2021-11-19 02:00 UTC, azuchi requested changes

2021-11-19 02:00 UTC, azuchi commented on README.md
> +    # The number of utxos in utxo pool.
max値についても記載しておきましょう。

2021-11-19 04:29 UTC, merged